### PR TITLE
fix(permission): permission error message is not readable

### LINKED ISSUE #2226: [Bug]: error message of resource role permission is not readable
### ODC version

4.2.4

### OB version

not related

### What happened?

1. create a new odc user
2. login odc based on this user
3. attempt visit a project that isn't belong to him/her
截屏2024-04-16 10 11 33

as you can see, the error message is not readable.

### What did you expect to happen?

the error message of resource role permission should be readable~

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by yhilmare**
#### What type of PR is this?

type-bug

#### What this PR does / why we need it:
error message of permission is not readable and this pr fix this issue~
#### Which issue(s) this PR fixes:

Fixes #2226 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ConnectionPermission.java [hunk 1]
```diff
@@ -119,7 +119,7 @@ protected void initPermissionMask(int mask) {
 
     @Override
     public String toString() {
-        return "ConnectionPermission " + this.resourceType + ":" + this.resourceId + " " + getActions(this.mask);
+        return ResourceType.ODC_CONNECTION.getLocalizedMessage() + ":" + this.resourceId + ": " + getActions(this.mask);
```
Comment (smallsheeeep) [inline server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ConnectionPermission.java:122]: Where does this copywriting come into play?

Comment (yhilmare) [reply server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ConnectionPermission.java:122]: `com.oceanbase.odc.core.authority.exception.AccessDeniedException`

**Review by smallsheeeep — APPROVED** [review]
