### PR TITLE
fix(database-change): failed to view a scheduled database change task with rollback plan in personal space

### LINKED ISSUE #414: [Bug]: Database changes cannot be viewed
### ODC version

odc4.2.0

### OB version

not have

### What happened?

Database change details cannot be viewed

### What did you expect to happen?

Can be viewed normally

### How can we reproduce it (as minimally and precisely as possible)?

Performing database changes in personal space，Select to generate a backup rollback plan during execution and select scheduled execution，View database change details after execution
image

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by PeachThinking**
#### What type of PR is this?
type-bug
module-database-change

#### What this PR does / why we need it:
after creating a scheduled database change task in personal space, the task details cannot be viewed after checking the option to generate a rollback plan.
The cause is `FlowInstanceService#buildWithoutApprovalNode` method incorrectly constructs `FlowInstance` when `rollbackPlanInstance` is added before the `service task`.

#### Which issue(s) this PR fixes:

Fixes #414

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yhilmare** [comment]
> fix(database-change): The task details cannot be viewed when creating a scheduled database change task in personal space and checking the option to generate rollback plan

this title is too long, may 'fix(database-change): failed to view a scheduled database change task with rollback plan in personal space'

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java [hunk 1]
```diff
@@ -624,20 +624,25 @@ private FlowInstanceDetailResp buildWithoutApprovalNode(CreateFlowInstanceReq fl
...
+                                strategyConfig);
+                taskInstance.setTargetTaskId(taskEntity.getId());
+                taskInstance.update();
                 FlowTaskInstance rollbackPlanInstance =
-                        flowFactory.generateFlowTaskInstance(flowInstance.getId(), false, false,
+                        flowFactory.generateFlowTaskInstance(flowInstance.getId(), true, false,
                                 TaskType.GENERATE_ROLLBACK, ExecutionStrategyConfig.autoStrategy());
                 taskConfigurer = flowInstance.newFlowInstance().next(rollbackPlanInstance).next(taskInstance);
             } else {
+                FlowTaskInstance taskInstance =
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java:641]: duplicated code

**Review by yhilmare — APPROVED** [review]
lgtm
