### PR TITLE
fix(migration): rule metadata migration will be triggered every time the ODC server starts up

### LINKED ISSUE #574: [Bug]: R42017RuleMetadataMigrate repeatly execute every start up
### ODC version

4.2.0/4.2.1

### OB version

not related

### What happened?

[2023-10-19 13:25:47.500][main][,,][INFO][com.oceanbase.odc.migrate.jdbc.common.R42017RuleMetadataMigrate][90]: remove regulation rules successfully, total removed rule count=49
[2023-10-19 13:26:19.313][main][,,][INFO][com.oceanbase.odc.migrate.jdbc.common.R42017RuleMetadataMigrate][95]: add new regulation rules successfully, total added rule count=49
[2023-10-19 13:26:19.314][main][,,][INFO][com.oceanbase.odc.core.migrate.Migrates][222]: migrate REPEATABLE JDBC 4.2.0.17 init regulation rule metadata done, result=true``

### What did you expect to happen?

R42017RuleMetadataMigrate should be executed one time  exactly,
we may use ODC version as the checksum for this Migration script.

### How can we reproduce it (as minimally and precisely as possible)?

restart odc server, check the odc.log

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by MarkPotato777**
#### What type of PR is this?

type-bug
module-migration

#### What this PR does / why we need it:
Rule metadata will be deleted and inserted once every time the ODC server starts up, while we expect that if there is no change between records in `regulation-rule-metadata.yaml` and in the metadb, we do not update the metadata.

The issue is that we only override the `equals()` and `hashCode()` method in `MetadataEntity` but do not override them in `PropertyMetadataEntity`.

#### Which issue(s) this PR fixes:

Fixes #574 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/metadb/regulation/ruleset/MetadataEntity.java [hunk 1]
```diff
@@ -99,20 +99,24 @@ public boolean equals(Object obj) {
             return false;
         }
         MetadataEntity that = (MetadataEntity) obj;
-        return Objects.equals(this.getId(), that.getId()) && Objects.equals(this.getBuiltIn(), that.getBuiltIn())
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/metadb/regulation/ruleset/MetadataEntity.java:102]: why don't we use `@EqualAndHashCode`, this class looks like a normal pojo class

Comment (MarkPotato777) [reply server/odc-service/src/main/java/com/oceanbase/odc/metadb/regulation/ruleset/MetadataEntity.java:102]: `MetadataEntity` contains a list of `PropertyMetadataEntity`, and what we need here is that if two lists of  `PropertyMetadataEntity` are the same list regardless of the order of the elements, then the two `MetadataEntity` entities are equal. I use CollectionUtils.isEqualCollection in the `equals` method to judge if these two `PropertyMetadataEntity` lists are equal. I doubt if `@EqualAndHashCode` could handle this scene.

Comment (yhilmare) [reply server/odc-service/src/main/java/com/oceanbase/odc/metadb/regulation/ruleset/MetadataEntity.java:102]: can we use `Set< PropertyMetadataEntity>` to regardless the sequence of the `PropertyMetadataEntity`?

**Review by yhilmare — APPROVED** [review]
lgtm

File: server/odc-service/src/main/java/com/oceanbase/odc/metadb/regulation/ruleset/MetadataEntity.java (hunk 1 above)
Comment (MarkPotato777) [reply server/odc-service/src/main/java/com/oceanbase/odc/metadb/regulation/ruleset/MetadataEntity.java:102]: Yes, using `Set` instead of `List` is a better choice here, but we need to change the `PropertyMetadataEntity`'s `defaultValues` and `candidates` from a list to set as well, and this modification may cause some other changes to the original code, so I prefer not to make this modification here.
