### PR TITLE
fix(sqlcheck): affected rows for the native MySQL INSERT statement cannot take effect

### LINKED ISSUE #3316: [Bug]: The native MySQL POST statement restricts the number of rows affected by SQL (estimated) and cannot take effect
### ODC version

odc432

### OB version

*

### What happened?

image
image

### What did you expect to happen?

image

### How can we reproduce it (as minimally and precisely as possible)?

Set limit on the number of rows affected by SQL (estimated), add data in native MySQL

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by yiminpeng**
What type of PR is this?

bugfix

What this PR does / why we need it:

added a new rule to deal with the unable to judge the affected rows.

restrict affected rows can not work when use insert statement.
because native mysql explain the insert ... statement have difference process from update/delete.

Process mode:
* case1: For INSERT INTO ... VALUES(...) statements, ODC checks the count of value list.
* case2: For INSERT INTO ... SELECT ... statements, ODC runs EXPLAIN statements to get affected rows.

Which issue(s) this PR fixes:

Fixes #3316 

Special notes for your reviewer:
```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java [hunk 1]
```diff
@@ -120,14 +122,38 @@ public List<DialectType> getSupportsDialectTypes() {
...
+     * ODC runs EXPLAIN statements to get affected rows.
+     *
+     * @param explainSql target sql
+     * @return affected rows
+     */
+    private long getMySqlAffectedRowsByCount(String explainSql, JdbcOperations jdbc) {
+
+        explainSql = explainSql.toLowerCase();
+
+        if (explainSql.contains("value")) {
```
Comment (yizhouxw) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:137]: what if sql statement contains other 'value' , e.g. identifer & string value

Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:137]: maybe we need to reconsider the matching strings here, e.g. only match `select`

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java [hunk 2]
```diff
@@ -120,14 +122,33 @@ public List<DialectType> getSupportsDialectTypes() {
...
+     * @return affected rows
+     */
+    private long getMySqlAffectedRowsByCount(String explainSql, JdbcOperations jdbc) {
+
+        explainSql = explainSql.toLowerCase();
+
+        if (explainSql.contains("select")) {
+            return getMySqlAffectedRowsByExplain(explainSql, jdbc);
+        } else {
+            return explainSql.split("\\),").length;
```
Comment (MarkPotato777) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:140]: The method is not robust.
Check `insert_stmt` in `OBParser.g4`, it contains a lot of syntaxes including '),'

Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:140]: Ok, I'll achieve it in a more accurate way.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java [hunk 3]
```diff
@@ -120,14 +124,51 @@ public List<DialectType> getSupportsDialectTypes() {
...
+     * @param sql target sql
+     * @return affected rows
+     */
+    private long getMySqlAffectedRowsByCount(String sql) {
+
+        sql = sql.trim().replace("\n", "").toUpperCase();
+        String valuesRegex = "\\)\\s*VALUES?\\s*\\(";
+        String selectRegex = "\\)\\s*SELECT";
+
+        Pattern valuesPattern = Pattern.compile(valuesRegex);
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:141]: we may compile them at static code block:
```java
private static Pattern VALUES_PATTERN = Pattern.compile(valuesRegex);
private static Pattern SELECT_PATTERN = Pattern.compile(selectRegex);
```

Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:141]: got it. It's best to use sql-parser, I didn't know it could be used like this before.

**Review by yizhouxw — DISMISSED** [review]
lgtm

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java [hunk 4]
```diff
@@ -120,14 +123,44 @@ public List<DialectType> getSupportsDialectTypes() {
...
+     * MySQL checks the count of value list. Process mode: case1: For INSERT INTO ... VALUES(...)
+     * statements, ODC checks the count of value list. case2: For INSERT INTO ... SELECT ... statements,
+     * ODC runs EXPLAIN statements to get affected rows.
+     *
+     * @param insertStatement target sql
+     * @return affected rows
+     */
+    private long getMySqlAffectedRowsByCount(Insert insertStatement) {
+
+        List<List<Expression>> insertList = insertStatement.getTableInsert().get(0)
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:136]: the logic here is not robustness, we should check three things:
1. InsertTable list is empty or not
2. InsertTable list is not empty and we should judge if the insertTable list is singleton
3. if the insert table list is singleton, we should get the first one of it
4. we should judge if the values is empty
5. if the values is empty we should judge whether it is select or const value

you can ref the `libs/ob-sql-parser/src/main/java/com/oceanbase/tools/sqlparser/statement/insert/InsertTable.java` to do this

**Comment by yhilmare** [comment]
we should add an another check rule to process the situation that we can not judge the affect rows or we failed to check the affect rows

File: server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml [hunk 5]
```diff
@@ -1422,4 +1422,29 @@
...
+    - label: SUB_TYPE
+      value: INSERT
+    - label: SUPPORTED_DIALECT_TYPE
+      value: OB_MYSQL
+    - label: SUPPORTED_DIALECT_TYPE
+      value: MYSQL
+  propertyMetadatas:
+    - name: ${com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.estimate-sql-affected-rows-failed.unable-to-estimate-sql-affected-count}
+      description: ${com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.estimate-sql-affected-rows-failed.unable-to-estimate-sql-affected-count.description}
+      type: INTEGER
```
Comment (yhilmare) [inline server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml:1447]: what's this input for?

Comment (yiminpeng) [reply server/odc-migrate/src/main/resources/init-config/init/regulation-rule-metadata.yaml:1447]: actually, `propertyMeatadatas`  it's not needed here.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java (hunk 4 above)
Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java]: got it and the work has been completed.

**Comment by yiminpeng** [comment]
> we should add an another check rule to process the situation that we can not judge the affect rows or we failed to check the affect rows

yes, when we failed to get the affected rows, we should give users a non-exception tips.

File: server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml [hunk 6]
```diff
@@ -1436,6 +1452,14 @@
...
     - 'MYSQL'
   propertiesJson: '{"${com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-sql-affected-rows.allowed-max-sql-affected-count}":1000}'
+- enabled: 1
+  level: 1
+  rulesetName: ${com.oceanbase.odc.builtin-resource.regulation.ruleset.default-prod-ruleset.name}
+  ruleName: ${com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.estimate-sql-affected-rows-failed.name}
+  appliedDialectTypes:
+    - 'OB_MYSQL'
+    - 'MYSQL'
+  propertiesJson: '{"${com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.estimate-sql-affected-rows-failed.unable-to-estimate-sql-affected-count}":-1}'
```
Comment (yhilmare) [inline server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml:1462]: why should we add this property? I think there is no parameter for this rule

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java [hunk 7]
```diff
@@ -76,17 +81,42 @@ public SqlCheckRuleType getType() {
     @Override
     public List<CheckViolation> check(@NonNull Statement statement, @NonNull SqlCheckContext context) {
 
+        long affectedRows = getAffectedRows(statement);
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:84]: we may extract a method to get affect row count

File: server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml (hunk 6 above)
Comment (yiminpeng) [reply server/odc-migrate/src/main/resources/init-config/init/regulation-rule-applying.yaml:1462]: right, actually this rule is no param, so `propertiesJson: {}` is what I should define ?

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java (hunk 7 above)
Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:84]: yes, that's what I did.

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 8]
```diff
@@ -527,6 +527,10 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-sql-affect
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-sql-affected-rows.allowed-max-sql-affected-count=Maximum Allowed SQL Affected Rows
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-sql-affected-rows.allowed-max-sql-affected-count.description=Maximum Allowed SQL Affected Rows
 
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.estimate-sql-affected-rows-failed.message=The number of rows affected by this SQL cannot be determined or failed to be determined.
```
[the remark this answers is not in the document]
Comment (yiminpeng) [reply server/odc-core/src/main/resources/i18n/BusinessMessages.properties:530]: done.

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 9]
```diff
@@ -527,6 +527,10 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-sql-affect
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.estimate-sql-affected-rows-failed.name=Unable to determine or failed to determine the number of lines affected by the statement
```
[the remark this answers is not in the document]
Comment (yiminpeng) [reply server/odc-core/src/main/resources/i18n/BusinessMessages.properties:531]: done.

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 10]
```diff
@@ -527,6 +527,10 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-sql-affect
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.estimate-sql-affected-rows-failed.description=SQL affected rows determination failed.
```
[the remark this answers is not in the document]
Comment (yiminpeng) [reply server/odc-core/src/main/resources/i18n/BusinessMessages.properties:532]: done.

**Review by yizhouxw — APPROVED** [review]

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/Unable2JudgeAffectedRowsFactory.java [hunk 11]
```diff
@@ -0,0 +1,51 @@
...
+    @Override
+    public SqlCheckRuleType getSupportsType() {
+        return SqlCheckRuleType.ESTIMATE_SQL_AFFECTED_ROWS;
+    }
+
+    @Override
+    public SqlCheckRule generate(@NonNull DialectType dialectType, Map<String, Object> parameters) {
+        String key = getParameterNameKey("allowed-max-sql-affected-count");
+        if (parameters == null || parameters.isEmpty() || parameters.get(key) == null) {
+            return new Unable2JudgeAffectedRows(1000L, dialectType, jdbc);
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/Unable2JudgeAffectedRowsFactory.java:47]: there is no parameter for this rule, please check~

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/SqlCheckRuleType.java [hunk 12]
```diff
@@ -247,7 +247,11 @@ public enum SqlCheckRuleType implements Translatable {
     /**
      * Restrict the number of lines affected by SQL
      */
-    RESTRICT_SQL_AFFECTED_ROWS("restrict-sql-affected-rows");
+    RESTRICT_SQL_AFFECTED_ROWS("restrict-sql-affected-rows"),
+    /**
+     * Unable to judge restrict the number of lines affected by SQL
+     */
+    ESTIMATE_SQL_AFFECTED_ROWS("estimate-sql-affected-rows-failed");
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/SqlCheckRuleType.java:254]: this rule type enum is confusing

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java [hunk 13]
```diff
@@ -49,11 +54,11 @@
 @Slf4j
 public class MySQLAffectedRowsExceedLimit implements SqlCheckRule {
 
-    private final Long maxSqlAffectedRows;
+    protected final Long maxSqlAffectedRows;
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:57]: we'd better maintain the private, same as above

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java [hunk 14]
```diff
@@ -76,17 +81,42 @@ public SqlCheckRuleType getType() {
...
+    /**
+     * Get supported database types
+     */
+    @Override
+    public List<DialectType> getSupportsDialectTypes() {
+        return Arrays.asList(DialectType.MYSQL, DialectType.OB_MYSQL);
+    }
+
+    protected long getAffectedRows(@NonNull Statement statement) {
+
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:106]: we may remove these meaningless breaking lines, same as below

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/Unable2JudgeAffectedRows.java [hunk 15]
```diff
@@ -0,0 +1,72 @@
...
+     * Execution rule check
+     */
+    @Override
+    public List<CheckViolation> check(@NonNull Statement statement, @NonNull SqlCheckContext context) {
+        try {
+            long affectedRows = super.getAffectedRows(statement);
+            if (affectedRows < 0) {
+                return Collections.singletonList(SqlCheckUtil
+                        .buildViolation(statement.getText(), statement, getType(),
+                                new Object[] {maxSqlAffectedRows, affectedRows}));
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/Unable2JudgeAffectedRows.java:60]: the i18n doc for this rule has no parameter, we'd better not input any parameters

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/Unable2JudgeAffectedRows.java [hunk 16]
```diff
@@ -0,0 +1,72 @@
...
+import com.oceanbase.odc.service.sqlcheck.SqlCheckUtil;
+import com.oceanbase.odc.service.sqlcheck.model.CheckViolation;
+import com.oceanbase.odc.service.sqlcheck.model.SqlCheckRuleType;
+import com.oceanbase.tools.sqlparser.statement.Statement;
+
+import lombok.NonNull;
+import lombok.extern.slf4j.Slf4j;
+
+@Slf4j
+public class Unable2JudgeAffectedRows extends MySQLAffectedRowsExceedLimit {
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/Unable2JudgeAffectedRows.java:34]: We’d better use composition instead of inheritance

Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/Unable2JudgeAffectedRows.java:34]: name suggestion: MySQLUnable2JudgeAffectedRows

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/Unable2JudgeAffectedRowsFactory.java (hunk 11 above)
Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/factory/Unable2JudgeAffectedRowsFactory.java:47]: got it, I will achieve it in another way.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/SqlCheckRuleType.java (hunk 12 above)
Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/model/SqlCheckRuleType.java:254]: fixed

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java (hunk 13 above)
Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:57]: got it

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java (hunk 14 above)
Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/MySQLAffectedRowsExceedLimit.java:106]: got it

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/Unable2JudgeAffectedRows.java (hunk 15 above)
Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/Unable2JudgeAffectedRows.java]: done.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/Unable2JudgeAffectedRows.java (hunk 16 above)
Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/Unable2JudgeAffectedRows.java]: ok, got it

**Review by MarkPotato777 — APPROVED** [review]

**Review by JessieWuJiexi — APPROVED** [review]

**Review by yhilmare — APPROVED** [review]
lgtm
