### PR TITLE
fix(data-transfer): read timout occurred when getting large for internal usage

### LINKED ISSUE #3759: [Bug]: the internal file transfer timeout is too short
### ODC version

4.2.4

### OB version

not related

### What happened?

1. upload a big file(more than 200MB) and startup a import task
2. use timer executor
截屏2024-10-30 11 08 50

3. make sure that the machine execute this task and the file to be uploaded is different
4. make sure that such exception is thrown
截屏2024-10-30 11 10 15
5. the user will find out that he/she will import nothing
lQLPJxIGn7mAduXNAhzNA3ewJPXrOoNpx3sHCHVwJJuWAA_887_540

### What did you expect to happen?

import csv normally

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by LuckyPickleZZ**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:

When getting internal file for datatransfer, the default timeout was 10s . This is to small. ODC allows importing up to 2 GB of files.  So We estimate a 5-minute timeout based on transmission rate of 10 MB/s.

#### Which issue(s) this PR fixes:

Fixes #3759

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DataTransferRuntimeFlowableTask.java [hunk 1]
```diff
@@ -45,6 +45,11 @@
 
 @Slf4j
 public class DataTransferRuntimeFlowableTask extends BaseODCFlowTaskDelegate<Void> {
+    /**
+     * ODC allows importing up to 2 GB of files. We estimate a 5-minute timeout based on transmission
+     * rate of 10 MB/s.
+     */
+    private static final int DEFAULT_GET_IMPORT_FILE_TIMEOUT_MILLIS = 300 * 1000;
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DataTransferRuntimeFlowableTask.java:52]: shall we make this parameter editable?

Comment (LuckyPickleZZ) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DataTransferRuntimeFlowableTask.java:52]: Under what circumstances do we need to modify this value?

**Review by yhilmare — APPROVED** [review]
lgtm
