### PR TITLE
fix(result-export): failed to export mysql data

### LINKED ISSUE #1271: [Bug]: Native MySQL import CSV file error
### ODC version

odc423

### OB version

*

### What happened?

image
log
[text (17).log](https://github.com/oceanbase/odc/files/13739589/text.17.log)

### What did you expect to happen?

Import was successful

### How can we reproduce it (as minimally and precisely as possible)?

Import CSV files into native MySQL

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by LuckyPickleZZ**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:
1. when import csv file with blank spaces in filename like 'da ta.csv', thie URL#getFile will get 'da%20da.csv', causing FileNotFoundException. So I use URL#toUri instead. 
2. there are some bugs in result-set-export for mysql datasource , I fixed them...

#### Which issue(s) this PR fixes:

Fixes #1271 #1268

### CODE REVIEW

File: server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/parameter/MySQLReaderPluginParameter.java [hunk 1]
```diff
@@ -33,17 +33,21 @@ public class MySQLReaderPluginParameter implements PluginParameter {
...
     // TODO private String splitPk;
-    /**
-     * must be singleton. If this field is specified, the DataX will ignore the other configurations
-     * such as table and column, and directly use the content of this configuration to filter the data.
-     */
-    private List<String> querySql;
 
     @Data
     @AllArgsConstructor
     public static class Connection {
```
Comment (LuckyPickleZZ) [inline server/plugins/task-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/task/mysql/datatransfer/job/datax/model/parameter/MySQLReaderPluginParameter.java:39]: rename

**Review by yhilmare — APPROVED** [review]
lgtm

**Review by yhilmare — APPROVED** [review]
lgtm
