### PR TITLE
fix(partition-plan): can not recognize the partition key's data type on mysql mode

### LINKED ISSUE #3016: [Bug]: can not recognize the partition key's data type on mysql mode
### ODC version

4.3.1

### OB version

not related 

### What happened?

1. create a partition table:
```sql
create table test_tbl1(
    id bigint,
    CREATE_TIME datetime
) partition by range columns(create_time) (
    partition p202407 values less than('2024-07-25 00:00:00')
);
```

as you can see the partition key reference a column but the case is different which is valid for mysql mode

2. attempt to start up a partition plan
截屏2024-07-25 15 47 54

as you can see, the datatype is wrong for the table.

### What did you expect to happen?

recognize the datatype correctly~

### How can we reproduce it (as minimally and precisely as possible)?

follow what happened

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by guowl3**
#### What type of PR is this?
type-bug

#### Which issue(s) this PR fixes:

Fixes #3016 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/datatype/BasePartitionKeyDataTypeFactory.java [hunk 1]
```diff
@@ -70,8 +70,8 @@ public DataType generate() {
          * assume that the partition key is a column
          */
         Map<String, DBTableColumn> colName2Col = this.dbTable.getColumns().stream()
-                .collect(Collectors.toMap(c -> unquoteIdentifier(c.getName()), c -> c));
-        DBTableColumn column = colName2Col.get(unquotedPartitionKey);
+                .collect(Collectors.toMap(c -> unquoteIdentifier(c.getName()).toLowerCase(), c -> c));
```
Comment (yhilmare) [inline server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/datatype/BasePartitionKeyDataTypeFactory.java:73]: we may modify `OBMySQLAutoPartitionExtensionPoint#unquoteIdentifier` directly to fix this~

Comment (yizhouxw) [reply server/plugins/task-plugin-ob-mysql/src/main/java/com/oceanbase/odc/plugin/task/obmysql/partitionplan/datatype/BasePartitionKeyDataTypeFactory.java:73]: Collectors.toMap may change to use TreeMap with CASE_INSENSITIVE Comparator

**Review by yhilmare — APPROVED** [review]
lgtm
