### PR TITLE
fix(flow): the disabled user can still approving or rejecting a flow

### LINKED ISSUE #2550: [Bug]: A deactivated user should not be able to select
### ODC version

ODC 4.3.0

### OB version

not related

### What happened?

A deactivated user should not be able to select
image

### What did you expect to happen?

A deactivated user should not be able to select

### How can we reproduce it (as minimally and precisely as possible)?

First deactivate a user, then set the library administrator, and the deactivated user appears in the list

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by smallsheeeep**
#### What type of PR is this?
type-bug
module-flow

#### What this PR does / why we need it:
For a disabled user, there are some issues:
1. The user can still be selected as the database owner;
2. In ticket list, the user still displaied as the flow approval candidates;
3. The user can still approve the flow.
This PR fixed it.

#### Which issue(s) this PR fixes:

Fixes #2550 #2548 

#### Special notes for your reviewer:
Self-test passed.

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yhilmare — APPROVED** [review]
lgtm

File: server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/model/Project.java [hunk 1]
```diff
@@ -122,6 +122,9 @@ public static class ProjectMember {
         @JsonProperty(access = Access.READ_ONLY)
         private String accountName;
 
+        @JsonProperty(access = Access.READ_ONLY)
+        private Boolean userEnabled;
```
Comment (MarkPotato777) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/model/Project.java:126]: It's a bit odd that the project has this `userEnabled` field. How should we understand this?

Comment (MarkPotato777) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/project/model/Project.java:126]: Oh sorry, I didn't see it was added to `ProjectMember` rather than `Project`. Then it's cool to me~

**Review by MarkPotato777 — APPROVED** [review]
LGTM

**Review by krihy — COMMENTED** [review]
Lgtm
