### PR TITLE
fix: fix failed to query data and sql rules changing is not recorded by audit event

### LINKED ISSUE #606: [Bug]: there is no audit event record about sql-check rule changing
### ODC version

4.2.1

### OB version

not releated

### What happened?

I change the sql-check settings and do not find any audit events.

### What did you expect to happen?

audit event can record this behavior.

### How can we reproduce it (as minimally and precisely as possible)?

1. change sql-check rule's setting.
2. view audit events.

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by yhilmare**
#### What type of PR is this?

type-bug
type-enhancement

#### What this PR does / why we need it:

1. remove sql check interceptor when query table data.
2. SQL security specification modifications are included in operational audits.
3. define a special error code and throw an exception when failed to query database's version

#### Which issue(s) this PR fixes:

Fixes #606 #605 #604 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java [hunk 1]
```diff
@@ -62,6 +62,7 @@
 @Component
 public class SqlCheckInterceptor implements SqlExecuteInterceptor {
 
+    public final static String NEED_SQL_CHECK_KEY = "NEED_SQL_CHECK_KEY";
```
Comment (yizhouxw) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java:65]: value expected to be 'NEED_SQL_CHECK' ?

File: server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventAction.java [hunk 2]
```diff
@@ -303,10 +303,9 @@ public enum AuditEventAction implements Translatable {
 
     UPDATE_DATASOURCE,
 
-    CREATE_PROJECT
+    CREATE_PROJECT,
 
-
-    ;
+    CHANGE_SQL_SECURITY_RULE;
```
Comment (yizhouxw) [inline server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventAction.java:308]: use `UPDATE_` prefix , follow current style.

and, should we distinguish SQL Check Rule & SQL Console Rule ?

Comment (yhilmare) [reply server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventAction.java:308]: both sql check rule and sql console rule use the same api to update and the auditing is based on API level interception, so that we can not distinguish SQL Check Rule & SQL Console Rule

File: server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java (hunk 1 above)
Comment (yhilmare) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/session/interceptor/SqlCheckInterceptor.java:65]: done

File: server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java [hunk 3]
```diff
@@ -262,6 +262,7 @@ public enum ErrorCodes implements ErrorCode {
      * DB Object
      */
     DBObjectMetadataMayNotAccurate,
+    FailedQueryDBVersion,
```
Comment (yizhouxw) [inline server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/ErrorCodes.java:265]: QueryDBVersionFailed

File: server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventType.java [hunk 4]
```diff
@@ -74,6 +74,8 @@ public enum AuditEventType implements Translatable {
 
     PROJECT_MANAGEMENT,
 
+    SQL_SECURITY_RULES_MANAGEMENT
```
Comment (smallsheeeep) [inline server/odc-core/src/main/java/com/oceanbase/odc/core/shared/constant/AuditEventType.java:77]: We are more inclined to use a single term such as `SQL_SECURITY_RULE_MANAGEMENT`

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 5]
```diff
@@ -279,6 +280,7 @@ com.oceanbase.odc.AuditEventType.UNKNOWN_TASK_TYPE=Unknown task type
 com.oceanbase.odc.AuditEventType.DATABASE_MANAGEMENT=Database management
 com.oceanbase.odc.AuditEventType.DATASOURCE_MANAGEMENT=Datasource management
 com.oceanbase.odc.AuditEventType.PROJECT_MANAGEMENT=Project management
+com.oceanbase.odc.AuditEventType.SQL_SECURITY_RULES_MANAGEMENT=SQL security rule management
```
Comment (smallsheeeep) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:283]: Same as above

**Review by yizhouxw — APPROVED** [review]
lgtm
