### PR TITLE
fix(result-set-export): failed to rewrite sql for mysql

### LINKED ISSUE #1282: [Bug]: Native MySQL export result set selection CSV and Excel format selection without column header cannot take effect
### ODC version

odc423

### OB version

*

### What happened?

9a2e91cc9f75a69da0a8a401d48d22fe
8e1632b60e90b3154aab00c77dee1928

### What did you expect to happen?

The exported result set has no column header

### How can we reproduce it (as minimally and precisely as possible)?

Native MySQL export result set settings do not include column headers

### Anything else we need to know?

_No response_

### Cloud

_No response_

### LINKED ISSUE #1283: [Bug]: The native MySQL export result set query result limit cannot take effect
### ODC version

odc423

### OB version

*

### What happened?

6d17d4542831750944f77fe692f63648
50aa8ffcec084f7821fe3c27cf91e797

### What did you expect to happen?

The limit on the number of query results is in effect

### How can we reproduce it (as minimally and precisely as possible)?

The limit on the number of query results is set to be smaller than the table data

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by LuckyPickleZZ**
Fix #1283 . When exporting result set, we would rewrite query sql into like `select * from (<original sql>) limit xxx` . 
In ob-mysql , this works normally. But in native mysql, this rewrite would get a syntax error 'Every derived table must have its own alias'. 
Therefore, we will add a `as  __ODC_INTERNAL_RESULT_SET__` into query to fix this.

Fix #1282 . When user set skip header, the `TxtWriterPluginParameter#header` field should not be set.

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/ResultSetExportPreprocessor.java [hunk 1]
```diff
@@ -53,15 +53,15 @@ public void process(CreateFlowInstanceReq req) {
...
+        preCheckSql(parameter, connectionConfig.getDialectType());
 
         PreConditions.validArgumentState(FILE_NAME_PATTERN.matcher(parameter.getFileName()).matches(),
                 ErrorCodes.BadArgument, null,
                 "File name must contain only letters, numbers, Chinese characters and \"._-\" ");
     }
 
-    private void preCheckSql(String sql, DialectType dialectType) {
+    private void preCheckSql(ResultSetExportTaskParameter parameter, DialectType dialectType) {
+        String sql = parameter.getSql();
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/ResultSetExportPreprocessor.java:64]: is the new code different from old version?

Comment (LuckyPickleZZ) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/schedule/flowtask/ResultSetExportPreprocessor.java:64]: I added `parameter.setSql(sqls.get(0));` at line 80.

**Comment by LuckyPickleZZ** [comment]
also fix #1292 , when table name is in Chinese, there are no content in exported file.

**Review by yhilmare — APPROVED** [review]
lgtm
