### PR TITLE
fix(dlm):wrong order status when task is rollback

### LINKED ISSUE #704: [Bug]: When executing a DLM task periodically, the status changes to Completed, resulting in no disable button.
### ODC version

ODC422

### OB version

independent

### What happened?

When executing a DLM task periodically, the status changes to Completed, resulting in no disable button.
image

### What did you expect to happen?

normally

### How can we reproduce it (as minimally and precisely as possible)?

Create periodic execution tasks

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by guowl3**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:
When a sub-task of a periodic work order is rolled back, the status of the work order will not be affected.
#### Which issue(s) this PR fixes:

Fixes #704

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java [hunk 1]
```diff
@@ -129,6 +130,12 @@ public void jobExecutionVetoed(JobExecutionContext context) {
     public void jobWasExecuted(JobExecutionContext context, JobExecutionException jobException) {
         JobKey key = context.getJobDetail().getKey();
         List<? extends Trigger> jobTriggers;
+        Optional<ScheduleEntity> scheduleEntityOptional =
+                scheduleRepository.findById(ScheduleTaskUtils.getScheduleId(context));
+        if (!scheduleEntityOptional.isPresent()
```
Comment (yizhouxw) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java:135]: a little hard to understand..

may split into 2 steps

if(!scheduleEntityOptional.isPresent() {
    // if unespected, log.warn here 
    return;
}

isRollbackTask=!key.getGroup().equals(scheduleEntityOptional.get().getJobType().name())
if (isRollbackTask) {
 return;
}

Comment (guowl3) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/quartz/OdcJobListener.java]: simplified the method and the key of the rollback task  not used to find the trigger now.

**Review by yizhouxw — APPROVED** [review]
lgtm
