### PR TITLE
fix(ticket): project owners failed to abort a ticket

### LINKED ISSUE #2387: [Bug]: The project owner and users with approvable permissions cannot terminate the task
### ODC version

ODC 424-bp1

### OB version

~

### What happened?

image
The project owner and users with approvable permissions cannot terminate the task.

### What did you expect to happen?

The project owner and users with approvable permissions can terminate the task.

### How can we reproduce it (as minimally and precisely as possible)?

The developer of the project executes a task and terminates it using the project owner.

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by yhilmare**
#### What type of PR is this?

type-bug

#### What this PR does / why we need it:
a ticket can only be aborted by its creator and I refactor this. a ticket can be aborted by its creator and project owner~
#### Which issue(s) this PR fixes:

Fixes #2387

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java [hunk 1]
```diff
@@ -555,12 +554,6 @@ public FlowInstanceDetailResp detail(@NotNull Long id) {
     @Transactional(rollbackFor = Exception.class)
     public FlowInstanceDetailResp cancel(@NotNull Long id, Boolean skipAuth) {
         FlowInstance flowInstance = mapFlowInstance(id, flowInst -> flowInst, skipAuth);
-        if (!skipAuth) {
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java:558]: this auth process is already done by `mapFlowInstance`, It is not necessary to do it again

**Review by yizhouxw — APPROVED** [review]
lgtm

**Review by krihy — COMMENTED** [review]
lgtm

**Review by krihy — APPROVED** [review]
