### PR TITLE
fix(db-browser): failed to list tables when ob's version is no greater than 2.2.30

### LINKED ISSUE #1476: [Bug]:There will be an error when creating the sql window using the ob2230 version.
### ODC version

ODC 4.2.3

### OB version

OB 2.2.3.0

### What happened?

There will be an error when creating the sql window using the ob2230 version.
image

### What did you expect to happen?

Open sql window without error.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by PeachThinking**
#### What type of PR is this?
type-bug
module-db-browser

#### What this PR does / why we need it:
1. ob oracle 2230 do not have `SYS.ALL_VIRTUAL_DATABASE_REAL_AGENT` internal table, In ob oracle mode, `ALL_TABLES` view information is uniformly queried to listTables.

2. fix get the DBSchemaAccessor for different versions

#### Which issue(s) this PR fixes:

Fixes #1476

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yhilmare** [comment]
pr title naming suggestion: failed to list table when ob's version is no greater than 2.2.30

File: server/odc-service/src/main/java/com/oceanbase/odc/service/db/browser/DBSchemaAccessors.java [hunk 1]
```diff
@@ -98,11 +98,11 @@ public static DBSchemaAccessor create(@NonNull JdbcOperations syncJdbcExecutor,
             if (VersionUtils.isGreaterThanOrEqualsTo(obVersion, "4.0.0")) {
                 // OB 版本 >= 4.0.0
                 return new OBOracleSchemaAccessor(syncJdbcExecutor, new ALLDataDictTableNames());
-            } else if (VersionUtils.isGreaterThanOrEqualsTo(obVersion, "2.2.7")) {
-                // OB 版本为 [2.2.7, 4.0.0)
+            } else if (VersionUtils.isGreaterThanOrEqualsTo(obVersion, "2.2.70")) {
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/db/browser/DBSchemaAccessors.java:101]: It should be a bug if method calling `VersionUtils.isGreaterThan("2.2.30", "2.2.7")` returns true.
@yizhouxw may check this?

**Review by yhilmare — COMMENTED** [review]
lgtm

**Review by yhilmare — APPROVED** [review]
lgtm
