### PR TITLE
fix(diagnose): failed to view query profile for distributed OB

### LINKED ISSUE #2828: [Bug]: Error reported after clicking TRACE ID after execution failure
### ODC version

odc431

### OB version

*

### What happened?

image
image
image

### What did you expect to happen?

TRACE ID not displayed

### How can we reproduce it (as minimally and precisely as possible)?

Click on TRACE ID after SQL execution failure

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by LuckyPickleZZ**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:

After testing query profile on a 3-node cluster, I found several issues in this case. The main works in this PR:
1. use session id, server ip, server port to accurately locate SQL plan records.
2. kill query if there is an exception when getting more results.
3. adapted to the execution plan on OB 4.2
4. added a variable to identify whether the current SQL supports viewing query profiles. The condition for this variable to be true is that the OB version is higher than 4.2.4 and the SQL type is `select`.

#### Which issue(s) this PR fixes:

Fixes #2828 #2852 #2869

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-core/src/main/java/com/oceanbase/odc/core/shared/model/ExecutorInfo.java [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+package com.oceanbase.odc.core.shared.model;
+
+import lombok.Data;
+
+/**
+ * @author: liuyizhuo.lyz
+ * @date: 2024/7/4
+ */
+@Data
+public class ExecutorInfo {
```
Comment (yhilmare) [inline server/odc-core/src/main/java/com/oceanbase/odc/core/shared/model/ExecutorInfo.java:25]: we may change another name, this name is occupied

File: server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java [hunk 2]
```diff
@@ -589,6 +592,13 @@ private SqlExecuteResult generateResult(@NonNull ConnectionSession connectionSes
         } catch (Exception e) {
             log.warn("Failed to init warning message", e);
         }
+        try {
+            String version = ConnectionSessionUtil.getVersion(connectionSession);
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java:596]: we may set this flag by checking if there is anything in connection session's cache~

File: server/odc-service/src/main/java/com/oceanbase/odc/service/session/OBExecutionListener.java [hunk 3]
```diff
@@ -31,16 +31,21 @@
...
 import com.oceanbase.tools.dbbrowser.parser.constant.SqlType;
+import com.oceanbase.tools.dbbrowser.parser.result.BasicResult;
+
+import lombok.extern.slf4j.Slf4j;
 
 /**
  * @author: liuyizhuo.lyz
  * @date: 2024/4/23
  */
+@Slf4j
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/session/OBExecutionListener.java:48]: we may change another name to tell the coder that this listener is only used for query profile~

File: server/odc-service/src/main/java/com/oceanbase/odc/service/session/OBExecutionListener.java [hunk 4]
```diff
@@ -92,14 +98,20 @@ private List<String> getSessionIds() {
...
+            return session.getSyncJdbcExecutor(CONSOLE_DS_KEY).execute((StatementCallback<List<String>>) stmt -> OBUtils
+                    .querySessionIdsByProxySessId(stmt, proxySessId, session.getConnectType()));
+        } catch (Exception e) {
+            log.warn("Failed to init session ids. Reason:{}", e.getMessage());
+            return Collections.emptyList();
+        }
     }
 
-    private boolean isSelect(SqlTuple sqlTuple) {
+    public static boolean isSqlTypeSupportProfile(SqlTuple sqlTuple) {
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/session/OBExecutionListener.java:110]: prefer not static~ and not public

File: server/odc-core/src/main/java/com/oceanbase/odc/core/shared/model/ExecutorInfo.java (hunk 1 above)
Comment (LuckyPickleZZ) [reply server/odc-core/src/main/java/com/oceanbase/odc/core/shared/model/ExecutorInfo.java]: sure, I renamed it into `OBExecutionServerInfo`

File: server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java (hunk 2 above)
Comment (LuckyPickleZZ) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java:597]: Sorry but I thought about it again, this cannot be changed. 
Perhaps this SQL actually supports viewing query profiles, but there is currently no record in the cache. Because the process of caching is asynchronous, we cannot guarantee it.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/session/OBExecutionListener.java (hunk 3 above)
Comment (LuckyPickleZZ) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/session/OBExecutionListener.java:48]: renamed to `OBQueryProfileExecutionListener`

**Review by yhilmare — DISMISSED** [review]
lgtm

**Review by yhilmare — APPROVED** [review]
lgtm

**Review by yizhouxw — APPROVED** [review]
lgtm
