### PR TITLE
fix(notification): fail to enqueue schedule event

### LINKED ISSUE #3964: [Bug]: Automatically run pending approval message notification not sent
### ODC version

ODC432

### OB version

 independent

### What happened?

Automatically run pending approval message notification not sent

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by LuckyPickleZZ**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:

Alter schedule task did not generate event

#### Which issue(s) this PR fixes:

Fixes #3964 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java [hunk 1]
```diff
@@ -242,6 +243,17 @@ private Event ofTask(TaskEntity task, TaskEvent status) {
                             : database.getEnvironment().getName(), database.getName()))
                     .collect(Collectors.joining(",")));
             labels.putIfNonNull(PROJECT_ID, projectId);
+        } else if (task.getTaskType() == TaskType.ALTER_SCHEDULE) {
+            AlterScheduleParameters parameter = JsonUtils.fromJson(task.getParametersJson(),
+                    AlterScheduleParameters.class);
+            ScheduleChangeParams scheduleChangeParams = parameter.getScheduleChangeParams();
+            Verify.notNull(scheduleChangeParams, "scheduleChangeParams");
+            ScheduleEntity schedule = scheduleRepository.findById(scheduleChangeParams.getScheduleId()).get();
```
Comment (MarkPotato777) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java:251]: `scheduleRepository.findById(scheduleChangeParams.getScheduleId()).get()` may return `null`? Better avoid NPE.

Comment (LuckyPickleZZ) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/notification/helper/EventBuilder.java]: 👍🏿 done

**Review by MarkPotato777 — APPROVED** [review]
LGTM
