### PR TITLE
fix(database): optimize error message of synchronizing databases failure

### LINKED ISSUE #773: [Bug]: The error message that fails to obtain the lock causes the failure of the database synchronization is inaccurate
### ODC version

4.2.1

### OB version

null

### What happened?

After clicking the synchronous database, error, and the error message causes customers to misunderstand:
image

### What did you expect to happen?

Optimize performance, optimize error messages

### How can we reproduce it (as minimally and precisely as possible)?

Synchronous database

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by MarkPotato777**
#### What type of PR is this?

type-bug

#### What this PR does / why we need it:
This PR optimizes error message of synchronizing databases failure.

#### Which issue(s) this PR fixes:

Fixes #773 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java [hunk 1]
```diff
@@ -354,7 +354,8 @@ public Boolean syncDataSourceSchemas(@NonNull Long dataSourceId) throws Interrup
     public Boolean internalSyncDataSourceSchemas(@NonNull Long dataSourceId) throws InterruptedException {
         Lock lock = jdbcLockRegistry.obtain(connectionService.getUpdateDsSchemaLockKey(dataSourceId));
         if (!lock.tryLock(3, TimeUnit.SECONDS)) {
-            throw new ConflictException(ErrorCodes.ResourceModifying, "Can not acquire jdbc lock");
+            throw new ConflictException(ErrorCodes.ResourceSynchronizing,
+                    new Object[] {ResourceType.ODC_DATABASE.getLocalizedMessage()}, "Can not acquire jdbc lock");
```
Comment (MarkPotato777) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java:358]: image

**Review by yhilmare — APPROVED** [review]
lgtm
