### PR TITLE
fix(permission):time is missing when initiating apply database task again

### LINKED ISSUE #3953: [Bug]: When you apply for library permissions and submit them again, the validity period of the permissions is different from the first time
### ODC version

4.3.3.

### OB version

no related

### What happened?

image
image
When you apply for a library permission, the permission is valid for 30 days when you submit it, and the permission for re-initiating the permission is valid for 7 days

### What did you expect to happen?

When re-initiated, the value of the permission validity period should be the same as the validity period selected for the first submission

### How can we reproduce it (as minimally and precisely as possible)?

Submit a database permission application, select a validity period of 30 days or another time, and initiate the request again to check whether the validity period of the newly generated ticket is the same as that of the first time

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by zijiacj**
#### What type of PR is this?
type-bug

#### Which issue(s) this PR fixes:

Fixes #3953

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/ApplyDatabaseParameter.java [hunk 1]
```diff
@@ -47,6 +47,10 @@ public class ApplyDatabaseParameter implements Serializable, TaskParameters {
      * Permission types to be applied for, required
      */
     private List<DatabasePermissionType> types;
+    /**
+     * This property is required by the front end to initiate task again
+     */
+    private String expireTimeValue;
```
Comment (MarkPotato777) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/permission/database/model/ApplyDatabaseParameter.java:53]: - `expireTimeValue` --> `validDuration`
- Clearly specify in the comment: This field represents the duration of the permission. It is only used for the front end to re-initiate tasks, and the backend does not rely on it.

**Review by MarkPotato777 — APPROVED** [review]
LGTM
