### PR TITLE
fix(dbbrowser): cant get correct ddl of procedure

### LINKED ISSUE #4023: [Bug]: After creating a stored procedure with parameter types set and enum, there is no value
### ODC version

odc433

### OB version

*

### What happened?

image
image

### What did you expect to happen?

There are values in ddl memory

### How can we reproduce it (as minimally and precisely as possible)?

Create a stored procedure and change the data type to set

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by zijiacj**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:
image
image

Currently, procedure's ddl is pieced together, and the above types of ddl will be displayed correctly.
An improved approach is to return the ddl that is retrieved directly from the database
#### Which issue(s) this PR fixes:

Fixes #4023 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java [hunk 1]
```diff
@@ -1350,14 +1350,22 @@ public DBProcedure getProcedure(String schemaName, String procedureName) {
                     .identifier(rs.getString("PARAMETER_NAME")).space()
                     .append(rs.getString("DTD_IDENTIFIER")).append(",");
         });
+        MySQLSqlBuilder getDDL = new MySQLSqlBuilder();
```
Comment (MarkPotato777) [inline libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java:1353]: 1. `parameters` is never used, the `queryForParameters` is unnecessary.
2. please add more unit tests for `getProcedure` to ensure the parser can handle the show create DDL.

Comment (zijiacj) [reply libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java:1353]: ok

**Review by MarkPotato777 — APPROVED** [review]
LGTM
