### PR TITLE
fix(database): database sync failed after updated an invalid datasource to a valid datasource

### LINKED ISSUE #2376: [Bug]: The data source did not set a connection timeout so that the database could not be synchronized after editing
### ODC version

ODC 4.2.4-bp2

### OB version

~

### What happened?

image
Create a data source with a connection timeout, then edit it as a normal data source, and synchronize the database with an error.

### What did you expect to happen?

Synchronize database successfully.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by MarkPotato777**
#### What type of PR is this?

type-bug

#### What this PR does / why we need it:
If the data source was previously failing to connect, changing it to a connectable data source will result in a database synchronization failure with the error message: "Data Source is synchronizing". The reason for this is that the JDBC lock from the last data source synchronization was never released, preventing other tasks from acquiring the lock. The lock was not released because` DataSource.getConnection` got stuck, even though we set the `connectTimeout` to `5000 ms`. It may be related to our ` DataSource.getLoginTimeout` always returning 0. The specific mechanism needs to be further discussed with our JDBC colleagues. 

This PR has just implemented a timeout mechanism at the service layer to ensure that deadlocks do not occur.

#### Which issue(s) this PR fixes:

Fixes #2376 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java [hunk 1]
```diff
@@ -512,11 +519,20 @@ private void syncTeamDataSources(ConnectionConfig connection) {
...
             }
-        } catch (SQLException e) {
+        } catch (ExecutionException e) {
             deleteDatabaseIfClusterNotExists(e, connection.getId(),
                     "update connect_database set is_existed = 0 where connection_id=?");
             throw new IllegalStateException(e);
+        } catch (Exception e) {
+            throw new IllegalStateException(e);
         } finally {
+            if (conn != null) {
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java:529]: we may shutdown the thread pool

File: server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java [hunk 2]
```diff
@@ -512,11 +519,20 @@ private void syncTeamDataSources(ConnectionConfig connection) {
                         "update connect_database set table_count=?, collation_name=?, charset_name=?, project_id=? where id = ?";
                 jdbcTemplate.batchUpdate(update, toUpdate);
             }
-        } catch (SQLException e) {
+        } catch (ExecutionException e) {
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/connection/database/DatabaseService.java:522]: we may get rootCause and judge if it is an instance of `SQLException`

**Review by yizhouxw — DISMISSED** [review]

**Review by yizhouxw — APPROVED** [review]
