### PR TITLE
fix(deployment): ODC_APP_EXTRA_ARGS not works

### LINKED ISSUE #2781: [Bug]: Startup parameter ODC_APP_EXTRA_ARGS does not work as expected
### ODC version

4.3.0

### OB version

4.2.1.6

### What happened?

When I was developing in integrating ODC in [ob-operator](https://github.com/oceanbase/ob-operator), I found that the startup argument `ODC_APP_EXTRA_ARGS` not working. 

(The following IP address is an internal mock one)

I set `ODC_APP_EXTRA_ARGS`="--odc.integration.bastion.account.query.request-url='http://10.42.0.1:18084/api/v1/auth/${account_verify_token}' --odc.integration.bastion.enabled='true' --odc.integration.bastion.account.auto-login-enabled='true' --odc.connect.database.sync.block-internal-database='false' --odc.database.schema.sync.exclude-schemas.ob-mysql=''"

And I found that the `sun.java.command` indeed contains the extra args in `odc.log`.

image

But the parameters do not work at all. I need to update them in the metadata database and restart odc server to make them work as expected.

### What did you expect to happen?

Parameters set in `ODC_APP_EXTRA_ARGS` work as expected. The bastion link could be opened normally.

### How can we reproduce it (as minimally and precisely as possible)?

Run odc server with environment variable `ODC_APP_EXTRA_ARGS` set to `--odc.integration.bastion.enabled='true' --odc.integration.bastion.account.auto-login-enabled='true'`, visit URL `http://xx.xx.xx.xx:8989/#/gateway/test` and you will found "session expired, please log in again". After login, visit the above URL again and you will get another error message.

image

image

If the parameters were set in metadata database and restart the odc server, the problem disappeared. 

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by yizhouxw**
#### What type of PR is this?

type-bug
#### What this PR does / why we need it:

ODC startup environment variable ODC_APP_EXTRA_ARGS does not works.

root cauase was RefreshScope mechasnim reload configuration from MetaDB config_system_configuration.

involved persistence process for configuration items set via ODC_APP_EXTRA_ARGS.

#### Which issue(s) this PR fixes:

Fixes #2781

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigBootstrap.java [hunk 1]
```diff
@@ -0,0 +1,92 @@
...
+                .filter(kv -> kv.length == 2)
+                .map(kv -> new Configuration(StringUtils.trim(kv[0]), StringUtils.trim(kv[1])))
+                .collect(Collectors.toList());
+    }
+
+    private void upsertSystemConfigurations(JdbcTemplate jdbcTemplate, List<Configuration> configurations) {
+        if (CollectionUtils.isEmpty(configurations)) {
+            return;
+        }
+        String sql = "INSERT INTO config_system_configuration (`key`, `value`) VALUES (?, ?) "
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigBootstrap.java:79]: Will this table `config_system_configuration` be created before this sql?

I mean when start up a total new odc~

Comment (yizhouxw) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigBootstrap.java:79]: yes, see `@DependsOn` annotation

**Review by yhilmare — APPROVED** [review]
lgtm

File: server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigBootstrap.java [hunk 2]
```diff
@@ -0,0 +1,92 @@
...
+@Component
+@DependsOn("metadbMigrate")
+public class SystemConfigBootstrap {
+    private static final int BATCH_SIZE = 100;
+
+    @Autowired
+    protected DataSource dataSource;
+
+    @PostConstruct
+    public void bootstrap() {
```
Comment (MarkPotato777) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigBootstrap.java:52]: What's the timing when these configurations are loading in the Spring Application Context? Will they take effect **right after** the odc-server starts up, or should we wait for the next config refresh?

Comment (yizhouxw) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigBootstrap.java:52]: after metadb migration, before odc server startup

Comment (MarkPotato777) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigBootstrap.java:52]: But will Spring be aware of this configuration change? Should we call `SystemConfigService.refresh` after these configs upsert to the table?

Comment (yizhouxw) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigBootstrap.java:52]: the configuration changed before spring context initialized

Comment (MarkPotato777) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/config/SystemConfigBootstrap.java:52]: got it.

**Review by MarkPotato777 — APPROVED** [review]
LGTM
