### PR TITLE
fix(database-change): create database change task failed in private sapce

### LINKED ISSUE #1693: [Bug]: Personal spatial database change execution failed
### ODC version

odc424

### OB version

*

### What happened?

image

### What did you expect to happen?

Execution succeeded

### How can we reproduce it (as minimally and precisely as possible)?

Personal space execution database changes

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by smallsheeeep**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:
This PR(#1578) cause a bug that cannot create a database change task in private space. The root cause is that flow instance created in private space has no PreCheck task. This PR just fix it.

#### Which issue(s) this PR fixes:

Fixes #1693 

#### Special notes for your reviewer:
Self-test passed.

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java [hunk 1]
```diff
@@ -208,20 +210,27 @@ private void modifyTimeoutIfTimeConsumingSqlExists(DelegateExecution execution,
...
-        if (Objects.nonNull(preCheckResult.getSqlCheckResult())
-                && preCheckResult.getSqlCheckResult().isTimeConsumingSqlExists()
-                && autoModifiedTimeout > parameters.getTimeoutMillis()) {
-            this.autoModifyTimeout = true;
-            parameters.setTimeoutMillis(autoModifiedTimeout);
-            TaskEntity databaseChangeTaskEntity = taskService.detail(taskId);
-            databaseChangeTaskEntity.setParametersJson(JsonUtils.toJson(parameters));
-            taskService.updateParametersJson(databaseChangeTaskEntity);
+        Optional<Long> preCheckTaskId;
+        try {
```
Comment (PeachThinking) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java:214]: we can set this parameter to true when create a database change task in personal space instead of by try catch: `parameters.isModifyTimeoutIfTimeConsumingSqlExists()`

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java [hunk 2]
```diff
@@ -732,6 +732,10 @@ private FlowInstanceDetailResp buildWithoutApprovalNode(CreateFlowInstanceReq fl
             ConnectionConfig connectionConfig) {
         log.info("Start creating flow instance, flowInstanceReq={}", flowInstanceReq);
         TaskType taskType = flowInstanceReq.getTaskType();
+        if (taskType == TaskType.ASYNC) {
```
Comment (yizhouxw) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java:735]: it also affect database change task generated by sql plan task ?

Comment (smallsheeeep) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java:735]: Yes! All task generated by this method has no PRE_CHECK task, so need add this `if` block.

**Comment by smallsheeeep** [comment]
BTW: The "modify timeout if time consuming SQL exists" is completed by using a built-in SQL check rule and will not take affect in Individual Space. This is not match user's needs and will be fixed in later PR by @PeachThinking

**Review by yhilmare — APPROVED** [review]
lgtm
