### PR TITLE
fix(sql-execute): fail to execute statement on OceanBase 2.2.30

### LINKED ISSUE #1475: [Bug]: When using the ob2230 version, an error occurs when executing sql.
### ODC version

ODC 4.2.3

### OB version

OB 2.2.3.0

### What happened?

When using the ob2230 version, an error occurs when executing sql.
image
image

### What did you expect to happen?

Use ob2230 version to execute sql successfully.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by LuckyPickleZZ**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:

`userenv('sessionid')` are not supported on OB 2230, so we use `OceanBaseConnection#getServerThreadId` instead.
But in `BaseSqlExecuteCallable` , the connection is generated from `SingleConnectionDataSource`. It's not instance of `OceanBaseConnection`. So we should get the real connection to get the id.

#### Which issue(s) this PR fixes:

Fixes #1475

### CODE REVIEW

File: server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleSessionExtension.java [hunk 1]
```diff
@@ -67,6 +69,9 @@ public String getConnectionId(Connection connection) {
         } catch (Exception e) {
             if (connection instanceof OceanBaseConnection) {
                 connectionId = ((OceanBaseConnection) connection).getServerThreadId() + "";
+            } else if (Proxy.isProxyClass(connection.getClass())) {
```
Comment (yhilmare) [inline server/plugins/connect-plugin-ob-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oboracle/OBOracleSessionExtension.java:72]: OBMySQLSessionExtension has the same problem

**Review by yhilmare — APPROVED** [review]
lgtm
