### PR TITLE
fix(import): add template api and supports mysql, oracle and doris datasource importing

### LINKED ISSUE #2726: [Bug]: Batch import of data sources can only select obmysql or oboracles
### ODC version

odc430

### OB version

*

### What happened?

image

### What did you expect to happen?

You can choose other types of data sources

### How can we reproduce it (as minimally and precisely as possible)?

Batch import data source download template, fill in content

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by yhilmare**
#### What type of PR is this?

type-bug

#### What this PR does / why we need it:
the datasource template is outdate and can not support mysql, oracle and doris importing.

I added two api to get the template of user and datasource importing which is stored by front end originally.
#### Which issue(s) this PR fixes:

Fixes #2726

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataSourceController.java [hunk 1]
```diff
@@ -178,6 +182,14 @@ public SuccessResponse<ConnectionPreviewBatchImportResp> previewBatchImportDataS
         return Responses.success(connectionBatchImportPreviewer.preview(file));
     }
 
+    @ApiOperation(value = "downloadDatasourceTemplate", notes = "Download Datasource Template File")
+    @RequestMapping(value = "/datasources/template", method = RequestMethod.GET)
```
Comment (yizhouxw) [inline server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataSourceController.java:186]: may POST  downloadBatchImportTemplate

File: server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java [hunk 2]
```diff
@@ -740,6 +749,20 @@ public boolean checkPermission(@NotNull Collection<Long> connectionIds, @NotNull
         return true;
     }
 
+    @SkipAuthorize
+    public BinaryDataResult getBatchImportTemplateFile() throws IOException {
+        String locale = LocaleContextHolder.getLocale().toLanguageTag().toLowerCase();
+        try (InputStream input = MySQLObjectNameUsingReservedWords.class.getClassLoader()
```
Comment (yizhouxw) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java:755]: what is the relationship with MySQLObjectNameUsingReservedWords?

File: server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataSourceController.java (hunk 1 above)
Comment (yhilmare) [reply server/odc-server/src/main/java/com/oceanbase/odc/server/web/controller/v2/DataSourceController.java:186]: btw, the other download apis are all 'GET' method~~

File: server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java (hunk 2 above)
Comment (yhilmare) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/connection/ConnectionService.java:755]: totally not, my fault, fixed~

**Review by yizhouxw — APPROVED** [review]
lgtm

**Review by PeachThinking — APPROVED** [review]
lgtm
