### PR TITLE
fix(function):The function does not display properly if the return value type is year

### LINKED ISSUE #3942: [Bug]: The data type returned by the function is inconsistent with the actual type
### ODC version

odc433

### OB version

*

### What happened?

image

### What did you expect to happen?

Should return to 2024

### How can we reproduce it (as minimally and precisely as possible)?

1. Create Function
create function `fun_year` (`p1` year) returns year
begin
  return p1;
end;
2. Execute function

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by zijiacj**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:
create function `fun_year` (`p1` year) returns year begin
return p1;
end;

In ob mysql tenant. The input and return parameters of the above function are both of the year type. The function is executed in black screen. the input and output are both 2024. However, the value obtained by jdbc using getString is 2024-01-01, which is inconsistent with black screen.

image
Current  the jdbc of `ob` specifies that the `year` type corresponds to `Short` in java, so changed from `getString` to `getShort`

For getting function execution results from database which dialect_type is `mysql`, use `JdbcRowMapper` to handle the type conversion

#### Which issue(s) this PR fixes:

Fixes #3942 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java [hunk 1]
```diff
@@ -269,7 +269,8 @@ public static JDBCType parseDataType(String dataType) {
                 || "SIGNTYPE".equalsIgnoreCase(dataType)
                 || "SIMPLE_INTEGER".equalsIgnoreCase(dataType)
                 || "MEDIUMINT".equalsIgnoreCase(dataType)
-                || "INTEGER".equalsIgnoreCase(dataType)) {
+                || "INTEGER".equalsIgnoreCase(dataType)
+                || "YEAR".equalsIgnoreCase(dataType)) {
             dataType = "INTEGER";
```
Comment (LioRoger) [inline server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java:274]: 1. we'd better distinguish parseDataType with db type. cause same type name in different db may represent different JDBCType.
2. why not fist check if we have matched the type, if not match then do if else logic match

Comment (zijiacj) [reply server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java:274]: That is the problem of the jdbc layer, I do that is just an opportunistic practice. I will communicate with people   responsible for jdbc to decide  the specific practice

Comment (zijiacj) [reply server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java]: image
have been parsed to `SMALLINT `,consistent with the jdbc specification

**Review by PeachThinking — COMMENTED** [review]
Have you discussed the feasibility of the solution to this problem with the jdbc teachers?

**Review by PeachThinking — APPROVED** [review]
lgtm

**Review by guowl3 — APPROVED** [review]
lgtm

File: server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java [hunk 2]
```diff
@@ -201,6 +201,14 @@ public static Object getValueFromStatement(CallableStatement statement, int inde
 
     public static Object getValueFromResultSet(ResultSet resultSet, int index, String type)
             throws SQLException {
+        // YEAR type is used to represent the year in 4-digit format. The range is 1901 to 2155, and 0000
```
Comment (LioRoger) [inline server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java:204]: I don't think add if before switch is a good solution.
YEAR is a special MySQL datatype, although it stored in integer, but is have some special usage.
eg year start begin 1900, and if you use in where clause, value less than 1900 is  special number need to be handled. So why not create it as a type and process it by type referenced function

Comment (zijiacj) [reply server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java:204]: image
image
The enum type `JDBCType` belongs to the package `java.sql`  and cannot be modified. The `year` type is not included

Comment (zijiacj) [reply server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java:204]: Using` getShort` will only get the values from 1901 to 2155 and 0

Comment (zijiacj) [reply server/odc-core/src/main/java/com/oceanbase/odc/core/sql/util/JdbcDataTypeUtil.java]: For getting function execution results from database which dialect_type is mysql, use `JdbcRowMapper` to handle the type conversion

**Review by LuckyPickleZZ — APPROVED** [review]
lgtm

File: server/odc-service/src/main/java/com/oceanbase/odc/service/db/util/OBMysqlCallFunctionCallBack.java [hunk 3]
```diff
@@ -76,23 +81,39 @@ public CallFunctionResp doInConnection(Connection con) throws SQLException, Data
...
+                if (CollectionUtils.size(rows) == 1 && Objects.nonNull(rows.get(0))
+                        && CollectionUtils.size(rows.get(0)) == 1) {
+                    CallFunctionResp callFunctionResp = new CallFunctionResp();
+                    PLOutParam plOutParam = new PLOutParam();
+                    plOutParam.setValue(String.valueOf(rows.get(0).get(0)));
                     plOutParam.setDataType(function.getReturnType());
                     callFunctionResp.setReturnValue(plOutParam);
+                    callFunctionResp.setOutParams(null);
                     return callFunctionResp;
+                } else {
```
Comment (MarkPotato777) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/db/util/OBMysqlCallFunctionCallBack.java:100]: The behavior changed if the resultset's size was not 1. Is it expected?

File: server/odc-service/src/main/java/com/oceanbase/odc/service/db/util/OBMysqlCallFunctionCallBack.java [hunk 4]
```diff
@@ -76,23 +81,39 @@ public CallFunctionResp doInConnection(Connection con) throws SQLException, Data
...
-            PLOutParam plOutParam = new PLOutParam();
             try (ResultSet res = stmt.executeQuery(sqlBuilder.toString())) {
                 if (!res.next()) {
-                    plOutParam.setValue(function.getReturnValue());
+                    return generateDefaultReturnValue();
+                }
+                JdbcQueryResult jdbcQueryResult = new JdbcQueryResult(res.getMetaData(), rowDataMapper);
+                jdbcQueryResult.addLine(res);
+                List<List<Object>> rows = jdbcQueryResult.getRows();
+                if (CollectionUtils.size(rows) == 1 && Objects.nonNull(rows.get(0))
```
Comment (MarkPotato777) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/db/util/OBMysqlCallFunctionCallBack.java:91]: Use org.apache.commons.collections4, then it can be simplified to 
`if (CollectionUtils.size(rows) == 1 && CollectionUtils.size(rows.get(0)) == 1)`

File: server/odc-service/src/main/java/com/oceanbase/odc/service/db/util/OBMysqlCallFunctionCallBack.java (hunk 3 above)
Comment (zijiacj) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/db/util/OBMysqlCallFunctionCallBack.java:100]: Not expected, should throw an exception

File: server/odc-service/src/main/java/com/oceanbase/odc/service/db/util/OBMysqlCallFunctionCallBack.java (hunk 4 above)
Comment (zijiacj) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/db/util/OBMysqlCallFunctionCallBack.java]: done

**Review by MarkPotato777 — APPROVED** [review]
LGTM

**Review by PeachThinking — APPROVED** [review]

**Review by guowl3 — APPROVED** [review]
lgtm
