### PR TITLE
fix(sql check):add two sql check rules for CREATE LIKE/AS statement

### LINKED ISSUE #3627: [Bug]: The sql check module does not match the create table xxx like statement
### ODC version

any

### OB version

unrelated

### What happened?

When the ‘create table xxx like’ statement is executed, no primary key error is displayed.
image

### What did you expect to happen?
Restrict the create table like statement in sql check or adapt it.

### How can we reproduce it (as minimally and precisely as possible)?

We can try the create table like statement to repeat.

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by zijiacj**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:
image
Two additional sql check rules in above picture have been added to handle these statements like 'create table a like b' and 'create table a as select * from b'  separately.
image
image
Those sql check rules in the four red boxes above shouldn‘t take effect for those statements.
#### Which issue(s) this PR fixes:

Fixes #3627 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 1]
```diff
@@ -785,6 +785,14 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.truncate-table-exis
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.truncate-table-exists.name=Truncate statement exists
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.truncate-table-exists.description=The truncate statement will clear table data and is very dangerous in a production environment. Please use it with caution.
 
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.create-table-like-exists.message=It is not recommended to use CREATE LIKE statement to create a table
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:788]: 所有的句子末尾都需要加上句号

Comment (zijiacj) [reply server/odc-core/src/main/resources/i18n/BusinessMessages.properties:788]: image
image
 the corresponding sentence will be rendered in the red box in the image above, So there is no need to add a period

Comment (zijiacj) [reply server/odc-core/src/main/resources/i18n/BusinessMessages.properties]: have done

**Review by LioRoger — COMMENTED** [review]
all you want to do is determinate if the sql is create table as/select statement. It's too heavy to use sql check rule to achieve If you add this two sqlCheck, it has affect to other code branch not needed this check.

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 2]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-in-expr.max-in-expr-count.description=The maximum number of expressions in the IN operation in the conditional predicate.
 
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-sql-affected-rows.message=The number of rows affected by this SQL statement exceeds the limit. Maximum Allowed Affected Rows: {0}; Estimated Affected Rows: {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-sql-affected-rows.name=Estimated SQL Affected Rows
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-sql-affected-rows.description=SQL affected rows cannot exceed the limit.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-sql-affected-rows.allowed-max-sql-affected-count=Maximum Allowed SQL Affected Rows
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-sql-affected-rows.allowed-max-sql-affected-count.description=Maximum Allowed SQL Affected Rows
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-sql-affected-rows.allowed-max-sql-affected-count.description=Maximum Allowed SQL Affected Rows.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:536]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 3]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-table-join.message=Too many table objects JOIN may lead to an unoptimized execution plan. It is recommended not to exceed {0}, the actual is {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-table-join.name=Too many table objects JOIN
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-table-join.description=Too many table objects JOIN may lead to an unoptimized execution plan
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-table-join.description=Too many table objects JOIN may lead to an unoptimized execution plan.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-table-join.max-join-table-count=Max join table count
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-table-join.max-join-table-count.description=Maximum number of table joins
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-table-join.max-join-table-count.description=Maximum number of table joins.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:546]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 4]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.no-not-null-exists-not-in.message=NOT NULL is required in the NOT IN condition to avoid falling into nested loops.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.no-not-null-exists-not-in.name=NOT NULL is required in the NOT IN condition
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.no-not-null-exists-not-in.description=NOT NULL is required in the NOT IN condition to avoid falling into nested loops
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.no-not-null-exists-not-in.description=NOT NULL is required in the NOT IN condition to avoid falling into nested loops.
 
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.no-valid-where-clause.message=Potential risk of constant true/false WHERE conditions in UPDATE/DELETE statements
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.no-valid-where-clause.message=Potential risk of constant true/false WHERE conditions in UPDATE/DELETE statements.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:552]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 5]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.no-valid-where-clause.name=No valid WHERE condition in UPDATE/DELETE statement
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.no-valid-where-clause.description=Potential risk of constant true/false WHERE conditions in UPDATE/DELETE statements
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.no-valid-where-clause.description=Potential risk of constant true/false WHERE conditions in UPDATE/DELETE statements.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:554]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 6]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-long-char-length.message=The length of the char type in the table definition is too long, it is recommended not to exceed {0}, the actual value is {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-long-char-length.name=Limit the length of char type fields
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-long-char-length.description=The length of the char type field should not be too long
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-long-char-length.description=The length of the char type field should not be too long.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-long-char-length.max-char-length=char maximum allowed length
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-long-char-length.max-char-length.description=char maximum allowed length
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-long-char-length.max-char-length.description=char maximum allowed length.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:592]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 7]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-unique-index-naming.message=The named {0} format of the unique index does not conform to the specification, pattern is {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-unique-index-naming.name=Restrict unique index name format
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-unique-index-naming.description=The standardized naming of unique indexes helps to improve the efficiency of database development, default is uk_${table-name}_${column-name-1}_${column-name-2}_...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-unique-index-naming.name-pattern=Unique index name regular expression
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-unique-index-naming.name-pattern.description=Unique index name regular expression
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-unique-index-naming.name-pattern.description=Unique index name regular expression.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:598]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 8]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.table-name-in-black-list.message=Table object cannot be named with {0}, the name is blacklisted at {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.table-name-in-black-list.name=Table names cannot be in the blacklist
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.table-name-in-black-list.description=The table name when creating the table, and the table name in the blacklist cannot be used when modifying the table name
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.table-name-in-black-list.description=The table name when creating the table, and the table name in the blacklist cannot be used when modifying the table name.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.table-name-in-black-list.black-list=Black list
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.table-name-in-black-list.black-list.description=Table Name blacklist
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.table-name-in-black-list.black-list.description=Table Name blacklist.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:616]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 9]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-charset.message=The character set {0} used by the table object is not in the allowed range. Allowed character sets include: {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-charset.name=Limit Table Character Set
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-charset.description=The charset used by the table object can only be selected from the options given in the whitelist
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-charset.description=The charset used by the table object can only be selected from the options given in the whitelist.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-charset.allowed-charsets=Allowed character sets
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-charset.allowed-charsets.description=Allowed character sets
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-charset.allowed-charsets.description=Allowed character sets.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:622]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 10]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-collation.message=The collation {0} used by the table object is not in the allowed range. Allowed collations include: {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-collation.name=Restricts the collation of table objects
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-collation.description=The collation used by the table object can only be selected from the options given in the whitelist
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-collation.description=The collation used by the table object can only be selected from the options given in the whitelist.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-collation.allowed-collations=Allowed collations
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-collation.allowed-collations.description=Allowed collations
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-collation.allowed-collations.description=Allowed collations.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:628]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 11]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-index.message=There are {0} column references in the index out of a maximum of {1} column references.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-index.name=Limit the number of columns included in a single index
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-index.description=The number of column references in a single index definition should not be excessive
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-index.description=The number of column references in a single index definition should not be excessive.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-index.max-column-ref-count=Maximum number of column references
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-index.max-column-ref-count.description=Maximum number of column references
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-index.max-column-ref-count.description=Maximum number of column references.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:634]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 12]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-datatypes.message=The primary key constraint involves a column whose type {0} is not allowed, allowed types include: {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-datatypes.name=Restrict primary key data type
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-datatypes.description=The columns involved in the primary key of the table must be of the data type defined in the rule
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-datatypes.description=The columns involved in the primary key of the table must be of the data type defined in the rule.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-datatypes.allowed-datatypes=Types allowed as primary keys
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-datatypes.allowed-datatypes.description=Types allowed as primary keys
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-datatypes.allowed-datatypes.description=Types allowed as primary keys.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:640]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 13]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-primary-key.name=Limit the number of columns included in primary key
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-primary-key.description=The number of column references in primary key definition should not be excessive
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-primary-key.description=The number of column references in primary key definition should not be excessive.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-primary-key.max-column-ref-count=Maximum number of column references
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-primary-key.max-column-ref-count.description=Maximum number of column references
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.too-many-column-refs-in-primary-key.max-column-ref-count.description=Maximum number of column references.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:646]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 14]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-auto-increment.message=Restrict primary key columns to auto-increment
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-auto-increment.message=Restrict primary key columns to auto-increment.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:648]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 15]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-auto-increment.name=Restrict primary key columns to auto-increment
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-auto-increment.description=Restrict primary key columns to auto-increment
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-auto-increment.description=Restrict primary key columns to auto-increment.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:650]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 16]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-naming.message=The named {0} format of the index does not conform to the specification, pattern is {1}
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-naming.message=The named {0} format of the index does not conform to the specification, pattern is {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-naming.name=Restrict index name format
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-naming.description=The standardized naming of indexes helps to improve the efficiency of database development, default is idx_${table-name}_${column-name-1}_${column-name-2}_...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-naming.name-pattern=Index name regular expression
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-naming.name-pattern.description=Index name regular expression
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-naming.name-pattern.description=Index name regular expression.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:656]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 17]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.column-collation-exists.name=Cannot set collation on column
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.column-collation-exists.description=Cannot set collation on column
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.column-collation-exists.description=Cannot set collation on column.
 
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.column-is-nullable.message=Columns of type {0} are not allowed to be null, and the data types of columns that are allowed to be null is: {1}
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.column-is-nullable.message=Columns of type {0} are not allowed to be null, and the data types of columns that are allowed to be null is: {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.column-is-nullable.name=Restrict column not nullable (NOT NULL)
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.column-is-nullable.description=Restrict columns to be non-nullable
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.column-is-nullable.description=Restrict columns to be non-nullable.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:676]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 18]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.column-is-nullable.nullable-datatype-list=Nullable column data types
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.column-is-nullable.nullable-datatype-list.description=Nullable column data types
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.column-is-nullable.nullable-datatype-list.description=Nullable column data types.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:678]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 19]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-column-name-case.message=The case setting of the column name {0} does not conform to the specification
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-column-name-case.message=The case setting of the column name {0} does not conform to the specification.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-column-name-case.name=Restrict column name case
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-column-name-case.description=Restrict column name case
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-column-name-case.description=Restrict column name case.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-column-name-case.is-uppercase=Whether to limit uppercase
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-column-name-case.is-uppercase.description=Whether to limit uppercase
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-column-name-case.is-uppercase.description=Whether to limit uppercase.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:700]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 20]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-column-name-case.is-lowercase=Whether to limit lowercase
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-column-name-case.is-lowercase.description=Whether to limit lowercase
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-column-name-case.is-lowercase.description=Whether to limit lowercase.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:702]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 21]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-name-case.message=The case setting of the table name {0} does not conform to the specification
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-name-case.message=The case setting of the table name {0} does not conform to the specification.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-name-case.name=Restrict table name case
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-name-case.description=Restrict table name case
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-name-case.description=Restrict table name case.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:706]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 22]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-name-case.is-uppercase=Whether to limit uppercase
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-name-case.is-uppercase.description=Whether to limit uppercase
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-name-case.is-uppercase.description=Whether to limit uppercase.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:708]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 23]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-name-case.is-lowercase=Whether to limit lowercase
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-name-case.is-lowercase.description=Whether to limit lowercase
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-name-case.is-lowercase.description=Whether to limit lowercase.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:710]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 24]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-auto-increment.message=The initial value of the auto-increment column of the restricted table is {0}, but the actual value is {1}
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-auto-increment.message=The initial value of the auto-increment column of the restricted table is {0}, but the actual value is {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-auto-increment.name=Restrict auto-increment initial value for table creation
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-auto-increment.description=Restrict auto-increment initial value for table creation
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-auto-increment.description=Restrict auto-increment initial value for table creation.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:714]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 25]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-auto-increment.init-value=Table auto-increment initial value
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-auto-increment.init-value.description=Table auto-increment initial value
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-table-auto-increment.init-value.description=Table auto-increment initial value.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:716]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 26]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.select-star-exists.description=SELECT statement is deprecated *.
 
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.missing-required-columns.message=Table is missing required column: {0}
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.missing-required-columns.message=Table is missing required column: {0}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.missing-required-columns.name=Table is missing required column
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.missing-required-columns.description=Table is missing required column
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.missing-required-columns.description=Table is missing required column.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.missing-required-columns.column-names=Collection of column names
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.missing-required-columns.column-names.description=Collection of column names
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.missing-required-columns.column-names.description=Collection of column names.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:726]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 27]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-naming.message=The named {0} format of the primary key does not conform to the specification, pattern is {1}
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-naming.message=The named {0} format of the primary key does not conform to the specification, pattern is {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-naming.name=Restrict primary key name format
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-naming.description=The standardized naming of PK helps to improve the efficiency of database development, default is pk_${table-name}_${column-name-1}_${column-name-2}_...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-naming.name-pattern=PK name regular expression
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-naming.name-pattern.description=PK name regular expression
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-pk-naming.name-pattern.description=PK name regular expression.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:746]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 28]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.prohibited-datatype-exists.message=Datatype {0} is forbidden, forbidden datatypes: {1}
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.prohibited-datatype-exists.message=Datatype {0} is forbidden, forbidden datatypes: {1}.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.prohibited-datatype-exists.name=Certain data types are prohibited
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.prohibited-datatype-exists.description=Certain data types are prohibited
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.prohibited-datatype-exists.description=Certain data types are prohibited.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.prohibited-datatype-exists.datatype-names=Prohibited data types
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.prohibited-datatype-exists.datatype-names.description=Prohibited data types
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.prohibited-datatype-exists.datatype-names.description=Prohibited data types.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:752]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 29]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-datatypes.name=Restricted Index Data Types
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-datatypes.description=Only columns of a specific data type can be referenced by the index, avoiding a large number of resources caused by incorrect indexing and serious performance problems
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-datatypes.description=Only columns of a specific data type can be referenced by the index, avoiding a large number of resources caused by incorrect indexing and serious performance problems.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-datatypes.allowed-datatypes=Allowed data types
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-datatypes.allowed-datatypes.description=Data types allowed in indexes
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-index-datatypes.allowed-datatypes.description=Data types allowed in indexes.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:758]: 非句子，去掉句号

File: server/odc-core/src/main/resources/i18n/BusinessMessages.properties [hunk 30]
```diff
@@ -506,285 +506,293 @@ com.oceanbase.odc.builtin-resource.regulation.rule.sql-console.external-sql-inte
...
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-auto-increment-datatypes.name=Limit optional data types for auto-increment columns
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-auto-increment-datatypes.description=The data type of columns marked as auto-increment should be carefully selected to avoid unexpected situations such as numerical overflow
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-auto-increment-datatypes.description=The data type of columns marked as auto-increment should be carefully selected to avoid unexpected situations such as numerical overflow.
 com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-auto-increment-datatypes.allowed-datatypes=Allowed data types
-com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-auto-increment-datatypes.allowed-datatypes.description=A collection of data types that allow columns to be marked as auto-increment
+com.oceanbase.odc.builtin-resource.regulation.rule.sql-check.restrict-auto-increment-datatypes.allowed-datatypes.description=A collection of data types that allow columns to be marked as auto-increment.
```
Comment (JessieWuJiexi) [inline server/odc-core/src/main/resources/i18n/BusinessMessages.properties:774]: 非句子，去掉句号

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/CreateTableAsExists.java [hunk 31]
```diff
@@ -0,0 +1,64 @@
...
+    }
+
+    @Override
+    public List<CheckViolation> check(@NonNull Statement statement, @NonNull SqlCheckContext context) {
+        if (!(statement instanceof CreateTable)) {
+            return Collections.emptyList();
+        }
+        CreateTable createTable = (CreateTable) statement;
+        if ((Objects.nonNull(createTable.getAs()))) {
+            return Collections.singletonList(SqlCheckUtil.buildViolation(
```
Comment (LioRoger) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/CreateTableAsExists.java:53]: is there any message to provided to this violation

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/CreateTableLikeExists.java [hunk 32]
```diff
@@ -0,0 +1,63 @@
...
+    }
+
+    @Override
+    public List<CheckViolation> check(@NonNull Statement statement, @NonNull SqlCheckContext context) {
+        if (!(statement instanceof CreateTable)) {
+            return Collections.emptyList();
+        }
+        CreateTable createTable = (CreateTable) statement;
+        if (Objects.nonNull(createTable.getLikeTable())) {
+            return Collections.singletonList(SqlCheckUtil.buildViolation(
```
Comment (LioRoger) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/CreateTableLikeExists.java:53]: is there any message to provided to this violation

File: server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/CreateTableAsExists.java (hunk 31 above)
Comment (zijiacj) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/sqlcheck/rule/CreateTableAsExists.java:53]: image
image
The framework is already written, just need to configure the above files

**Review by LioRoger — APPROVED** [review]
lgtm

**Review by guowl3 — APPROVED** [review]

**Review by JessieWuJiexi — APPROVED** [review]

**Review by PeachThinking — APPROVED** [review]
lgtm
