### PR TITLE
fix(schema): enable syncing databases by datasource in sql console

### LINKED ISSUE #3442: [Bug]: Synchronous metadb function of object tree list has delay
### ODC version

ODC 4.3.2

### OB version

No related.

### What happened?

I created a database in the SQL console and clicked the synchronization metabase button of the object tree, but the object tree did not show the new database.
image

### What did you expect to happen?

After clicking Synchronize Metabase, the database list is updated in time.

### How can we reproduce it (as minimally and precisely as possible)?

Follow what happened.

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by zijiacj**
#### What type of PR is this?
type-bug

#### Which issue(s) this PR fixes:

Fixes #3442
#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java [hunk 1]
```diff
@@ -201,6 +203,12 @@ public Boolean syncDatabaseObjects(@NonNull @Valid SyncDBObjectReq req) {
         this.databaseService.refreshExpiredPendingDBObjectStatus();
         Set<Database> databases = new HashSet<>();
         if (req.getResourceType() == ResourceType.ODC_CONNECTION) {
+            try {
+                databaseService.internalSyncDataSourceSchemas(req.getResourceId());
+            } catch (InterruptedException ex) {
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java:208]: catch exception instead

File: server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java [hunk 2]
```diff
@@ -201,6 +203,12 @@ public Boolean syncDatabaseObjects(@NonNull @Valid SyncDBObjectReq req) {
...
+                log.warn("sync all data bases of data base source: " + req.getResourceId() + " failed, errorMessage={}",
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java:209]: log.warn("sync data sources failed, datasourceId={}, errorMessage={}", req.getResourceID(), ex.getMsg())

File: server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java (hunk 1 above)
Comment (zijiacj) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java:208]: It is recommended to return the error directly if not getting the lock, because if not getting the lock, it may not be the latest database collection in odc, so it is meaningless to synchronize the database object like table ,view etc later.
What's more, even if successful, the list of databases is still not up to date.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java (hunk 2 above)
Comment (zijiacj) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/db/schema/DBSchemaIndexService.java:209]: ok

**Review by PeachThinking — COMMENTED** [review]
lgtm
