### PR TITLE
fix(security): http request during integration may receive SSRF attack

### LINKED ISSUE #170: [Bug]: Http request during external integration may receive SSRF attack
### ODC version

4.2.0

### OB version

Regardless of OB version

### What happened?

Http request during external integration may receive SSRF attack

### What did you expect to happen?

Check the url is in whitelist

### How can we reproduce it (as minimally and precisely as possible)?

-

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by smallsheeeep**
#### What type of PR is this?
type-bug
module-External integration

#### What this PR does / why we need it:
Check the url in whitelist when request to external URL

#### Which issue(s) this PR fixes:
Fixes #170

### CODE REVIEW

File: server/odc-server/src/main/resources/data.sql [hunk 1]
```diff
@@ -683,3 +683,9 @@ INSERT INTO config_system_configuration ( `key`, `value`, `description` ) VALUES
 
 INSERT INTO config_system_configuration ( `key`, `value`, `description` ) VALUES( 'odc.data-security.masking.enabled', 'true', '是否开启数据脱敏，默认为开启' ) ON DUPLICATE KEY UPDATE `id` = `id`;
 INSERT INTO config_system_configuration ( `key`, `value`, `description` ) VALUES( 'odc.task.partition-plan.schedule-cron', '0 0 * * * ?', '默认调度周期：每天 0 点' ) ON DUPLICATE KEY UPDATE `id` = `id`;
+
+--
+-- v4.2.1
+--
+INSERT INTO config_system_configuration(`key`, `value`, `description`) VALUES('odc.integration.url-white-list',
+ '', 'ODC 外部集成允许访问的 URL 白名单，配置集成 API 时只允许使白名单内的 URL，防止 SSRF 安全漏洞。默认为空，表示允许所有访问所有 URL') ON DUPLICATE KEY UPDATE `id`=`id`;
```
Comment (MarkPotato777) [inline server/odc-server/src/main/resources/data.sql:691]: description in English instead?

Comment (smallsheeeep) [reply server/odc-server/src/main/resources/data.sql]: yes my lord 🤓

**Review by yizhouxw — APPROVED** [review]
LGTM
