### PR TITLE
enhancement(flowable): adding indexes to improve query efficiency of flowable

### LINKED ISSUE #2496: [Bug]: The efficiency of querying flowInstance in the list is low.
### ODC version

*

### OB version

*

### What happened?

The efficiency of querying flowInstance in the list is low.

### What did you expect to happen?

Improve query efficiency

### How can we reproduce it (as minimally and precisely as possible)?

can‘t

### Anything else we need to know?

sql eg.
```
SELECT DISTINCT flowinstan0_.id AS id1_47_, flowinstan0_.create_time AS create_t2_47_, flowinstan0_.creator_id AS creator_3_47_, flowinstan0_.description AS descript4_47_, flowinstan0_.flow_config_id AS flow_con5_47_
	, flowinstan0_.flow_config_snapshot_xml AS flow_con6_47_, flowinstan0_.name AS name7_47_, flowinstan0_.organization_id AS organiza8_47_, flowinstan0_.parent_instance_id AS parent_i9_47_, flowinstan0_.process_definition_id AS process10_47_
	, flowinstan0_.process_instance_id AS process11_47_, flowinstan0_.project_id AS project12_47_, flowinstan0_.status AS status13_47_, flowinstan0_.task_type AS task_ty14_47_, flowinstan0_.update_time AS update_15_47_
FROM list_flow_instance_view flowinstan0_
	LEFT JOIN flow_instance_approval_view approvals1_ ON flowinstan0_.id = approvals1_.flow_instance_id
WHERE 1 = 1
	AND flowinstan0_.organization_id = ?
	AND 1 = 1
	AND flowinstan0_.create_time > ?
	AND flowinstan0_.create_time < ?
	AND 1 = 1
	AND 1 = 1
	AND flowinstan0_.task_type IN (
    'EXPORT', 
    'IMPORT', 
    'MOCKDATA', 
    'ASYNC', 
    'SHADOWTABLE_SYNC', 
    'PARTITION_PLAN', 
    'ONLINE_SCHEMA_CHANGE', 
    'ALTER_SCHEDULE', 
    'EXPORT_RESULT_SET', 
    'APPLY_PROJECT_PERMISSION', 
    'APPLY_DATABASE_PERMISSION', 
    'STRUCTURE_COMPARISON'
  )
	AND (flowinstan0_.project_id IN (?)
       OR flowinstan0_.project_id IN (?)
       AND (approvals1_.resource_role_identifier IN (?)
         AND approvals1_.approval_status IN (
           'COMPLETED', 
           'EXECUTING', 
           'EXPIRED', 
           'FAILED', 
           'WAIT_FOR_CONFIRM', 
           'CANCELLED'
         )
         OR flowinstan0_.creator_id = ?))
GROUP BY flowinstan0_.id, flowinstan0_.task_type
ORDER BY flowinstan0_.id DESC
```

### PR DESCRIPTION
**Pull request by LuckyPickleZZ**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:

ODC would query a `flow_instance_approval_view` view, which is generated by two table joining.  One of the join columns is `flow_instance_node_approval.flow_instance_id` . But there is no index on this column.

#### Which issue(s) this PR fixes:

Fixes #2496

### CODE REVIEW

**Review by yhilmare — DISMISSED** [review]
lgtm

File: server/odc-migrate/src/main/resources/migrate/common/V_3_3_0_1__add_flow.sql [hunk 1]
```diff
@@ -31,7 +31,8 @@ create table if not exists `flow_instance_node_approval` (
     `is_start_endpoint` tinyint NOT NULL COMMENT 'Describes whether this endpoint is the starting endpoint of the process',
     `is_end_endpoint` tinyint NOT NULL COMMENT 'Describes whether this endpoint is the end endpoint of the process',
     `flow_instance_id` bigint(20) NOT NULL comment 'Process instance id, references flow_instance(id)',
-    constraint pk_flow_instance_node_approval primary key (`id`)
+    constraint pk_flow_instance_node_approval primary key (`id`),
```
Comment (yizhouxw) [inline server/odc-migrate/src/main/resources/migrate/common/V_3_3_0_1__add_flow.sql:34]: it will not works, please do not modify versional script, all scripts start with`V_` will be only executed once

Comment (yhilmare) [reply server/odc-migrate/src/main/resources/migrate/common/V_3_3_0_1__add_flow.sql]: changed

**Review by yizhouxw — APPROVED** [review]
lgtm

**Review by yhilmare — APPROVED** [review]
lgtm
