### PR TITLE
fix(integration): cannot deal with array when parsing json or xml response

### LINKED ISSUE #1006: [Bug]: If the XML contains multiple identical node fields, the external approval configuration cannot find the corresponding fields.
### ODC version

ODC423

### OB version

independent

### What happened?

If the XML contains multiple identical node fields, the external approval configuration cannot find the corresponding fields.
image
image

### What did you expect to happen?

Tip optimization

### How can we reproduce it (as minimally and precisely as possible)?

chat privately

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by smallsheeeep**
#### What type of PR is this?
type-bug
module-integration

#### What this PR does / why we need it:
In ODC 4.2.3, if the response of external system is:
```json
{
    "company": {
        "employee": [
            {
                "id": "1",
                "name": "John Doe",
                "department": "Engineering",
                "skills": {
                    "skill": [
                        "Java",
                        "Python",
                        "SQL"
                    ]
                }
            },
            {
                "id": "2",
                "name": "Jane Smith",
                "department": "Marketing",
                "skills": {
                    "skill": [
                        "Marketing Strategy",
                        "Communication",
                        "Analytics"
                    ]
                }
            }
        ]
    }
}
```
Then we cannot deal with the array, because I have not use `ExpressionParser` in a right way and only support use SpEL like `[company][employee]`. In this PR, I fix it. And you can use SpEL like `company.employee[0].skills.skill[1]` which is easier for common user.

By the way, I refine the `xmlToJson` and `jsonToXml` methods by using `org.json`, and the dependency `jackson-dataformat-xml` is removed. Bucause the XML file root tag will be ignored by `XmlMapper` inner `jackson-dataformat-xml` which is not a right performance.

#### Which issue(s) this PR fixes:

Fixes #1006 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-common/src/main/java/com/oceanbase/odc/common/json/JsonUtils.java [hunk 1]
```diff
@@ -164,12 +164,25 @@ public static String xmlToJson(String xml) {
...
         try {
-            XmlMapper xmlMapper = new XmlMapper();
-            JsonNode jsonNode = xmlMapper.readTree(xml.getBytes());
-            ObjectMapper objectMapper = new ObjectMapper();
-            return objectMapper.writeValueAsString(jsonNode);
-        } catch (IOException e) {
-            log.error("failed to convert xml to json string, reason:{}", e.getMessage());
+            return XML.toJSONObject(xml).toString();
+        } catch (Exception e) {
+            log.error("failed to convert json to xml string, reason:{}", e.getMessage());
```
Comment (yhilmare) [inline server/odc-common/src/main/java/com/oceanbase/odc/common/json/JsonUtils.java:169]: log.warn will be better, you may change this in your next pr
