### PR TITLE
fix(parser): failed to recognize the schema or package name from an anonymous block

### LINKED ISSUE #3064: [Bug]:  access control not valid in anonymous sql block
### ODC version

4.2.4

### OB version

4.x oracle mode

### What happened?

current env:
    database: aps
    user access authority: no

in anonymous blocks:
     execute sql:
```sql
     declare
        i number;
    begin
      update aps.base_logs t set t.last_update_time = sysdata where t.id = 1;
       commit;
    end;
```
sql expected to be blocked cause not access authority granted to aps database

### What did you expect to happen?

anonymous sql block should also check access authority

### How can we reproduce it (as minimally and precisely as possible)?

current env:
    database: aps
    user access authority: no

in sql console
execute sql:
```
    update aps.base_logs t set t.last_update_time = sysdata where t.id = 1
```
result:
     sql was blocked cause write authority not granted

in anonymous blocks:
     execute sql:
```sql
     declare
        i number;
    begin
      update aps.base_logs t set t.last_update_time = sysdata where t.id = 1;
       commit;
    end;
```
sql expected to be blocked as sql console does but was execute successful

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by yhilmare**
#### What type of PR is this?

type-bug

#### What this PR does / why we need it:
failed to recognize the schema or package name from an anonymous block

#### Which issue(s) this PR fixes:

Fixes #3064

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java [hunk 1]
```diff
@@ -420,6 +421,18 @@ public RelationFactor visitPl_schema_name(Pl_schema_nameContext ctx) {
             return null;
         }
 
+        @Override
+        public RelationFactor visitSql_stmt(Sql_stmtContext ctx) {
+            try {
+                OBOracleRelationFactorVisitor visitor = new OBOracleRelationFactorVisitor();
+                visitor.visit(ctx.getChild(0).getChild(0));
```
Comment (LioRoger) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java:428]: is there any possible that ctx.getChild(0) is null or ctx.getChild() is zero length?

Comment (yhilmare) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/session/util/DBSchemaExtractor.java]: yes, you are right, I have changed it~

**Review by yizhouxw — APPROVED** [review]
lgtm
