### PR TITLE
fix(db-browser): adaption for ALL_TAB_COLS.USER_GENERATED in ob oracle

### LINKED ISSUE #1771: [Enhancement]: The creation of DBSchemaAccessor is expected to be placed in the db-browser layer
### What would you like to be added?

The structure of DBSchemaAccessor is placed in the db-browser layer

### Why is this needed?

Optimize code

### LINKED ISSUE #2208: [Bug]: show system generated column in SYS.ALL_TAB_COLS after alter drop column
### ODC version

4.2.4

### OB version

4.2.1.4

### What happened?

image

### What did you expect to happen?

image

or

image

don't show system generated column

### How can we reproduce it (as minimally and precisely as possible)?

alter drop column in table in odc, then show table columns in left tree

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by PeachThinking**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:
1. Fixes #2208 : 
    ob 4.1.0 and above version `ALL_TAB_COLS` adds the `USER_GENERATED` field. If it is a deleted column, then `USER_GENERATED = 'YES'`， these columns do not need to be displayed on a white screen on ODC to the user. The new `oboracle_4_1_x.yaml` is added to filter the `USER_GENERATED` field. At the same time, `OBOracleBetween4000And4100SchemaAccessor` is added.
2. Enhancement for #1771 ：
   put the creation of `DBSchemaAccessor`  in db-browser layer ：`DBSchemaAccessorGenerator`
   put the creation of `DBStatsAccessor`  in db-browser layer ：`DBStatsAccessorGenerator`
   put the creation of `DBObjectEditor`  in db-browser layer ：`DBObjectEditorGenerator`
   put the creation of `DBObjectTemplate`  in db-browser layer ：`DBObjectTemplateGenerator`

#### Which issue(s) this PR fixes:

Fixes #2208
Fixes #1771

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

**Comment by yhilmare** [comment]
please upgrade db-browser's version~

**Comment by PeachThinking** [comment]
> please upgrade db-browser's version~

Done～

File: libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessorGenerator.java [hunk 1]
```diff
@@ -0,0 +1,106 @@
...
+
+/**
+ * @author jingtian
+ * @date 2024/4/16
+ */
+public class DBSchemaAccessorGenerator {
+    public static DBSchemaAccessor createForOBOracle(@NonNull JdbcOperations jdbcOperations,
+            @NonNull String dbVersion) {
+        if (VersionUtils.isGreaterThanOrEqualsTo(dbVersion, "4.1.0")) {
+            // OB 版本 >= 4.1.0
```
Comment (MarkPotato777) [inline libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessorGenerator.java:47]: better use English

File: libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_1_x.yaml [hunk 2]
```diff
@@ -0,0 +1,277 @@
+sqls:
```
Comment (MarkPotato777) [inline libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_1_x.yaml:1]: Does this column only exists in OB 4.1.0? Is it an Oracle-compatibility feature?

**Review by LuckyPickleZZ — APPROVED** [review]
lgtm

File: libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessorGenerator.java (hunk 1 above)
Comment (PeachThinking) [reply libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/DBSchemaAccessorGenerator.java]: ok~

File: libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_1_x.yaml (hunk 2 above)
Comment (PeachThinking) [reply libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_1_x.yaml:1]: The USER_GENERATED field is only exists in ob versions 4.1.0 and above. It is a feature of the ob oracle kernel. Oracle does not have this field.

File: libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleLessThan400SchemaAccessor.java [hunk 3]
```diff
@@ -50,7 +50,7 @@
  * @Description: 适用于的 OB 版本：[2270, 400)
  */
 @Slf4j
-public class OBOracleLessThan400SchemaAccessor extends OBOracleSchemaAccessor {
+public class OBOracleLessThan400SchemaAccessor extends OBOracleBetween4000And4100SchemaAccessor {
```
Comment (yhilmare) [inline libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleLessThan400SchemaAccessor.java:53]: so, is there any differences between extending `OBOracleSchemaAccessor` and extending`OBOracleBetween4000And4100SchemaAccessor`?

File: libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_1_x.yaml [hunk 4]
```diff
@@ -0,0 +1,277 @@
...
+  list-basic-table-columns: |-
```
Comment (yhilmare) [inline libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_1_x.yaml:2]: we may figure out a way to avoid these too much duplicated sql statement in different yaml

**Comment by yhilmare** [comment]
there are several conflicts between your branch and dev/4.3.0

File: libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_1_x.yaml [hunk 5]
```diff
@@ -0,0 +1,277 @@
...
+    SELECT
+      OWNER,
+      TABLE_NAME,
+      COLUMN_NAME,
+      DATA_TYPE,
+      COMMENTS
+    FROM
+      SYS.ALL_TAB_COLS NATURAL JOIN SYS.ALL_COL_COMMENTS
+    WHERE
+      OWNER = ? AND TABLE_NAME = ? AND USER_GENERATED='YES'
```
Comment (yhilmare) [inline libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_1_x.yaml:12]: so, I get two questions:
1. is column 'USER_GENERATED' a new column after OB 4.1.0 and not appear before OB 4.1.0?
2. why are 'list-basic-view-columns' and 'list-basic-schema-view-columns' not filtered by this column?

File: server/odc-service/src/main/java/com/oceanbase/odc/service/db/browser/DBSchemaAccessors.java [hunk 6]
```diff
@@ -80,47 +67,19 @@ public static DBSchemaAccessor create(ConnectionSession connectionSession, Strin
...
-                return new OBOracleSchemaAccessor(syncJdbcExecutor, new ALLDataDictTableNames());
-            } else if (VersionUtils.isGreaterThanOrEqualsTo(dbVersion, "2.2.70")) {
-                // OB 版本为 [2.2.70, 4.0.0)
-                return new OBOracleLessThan400SchemaAccessor(syncJdbcExecutor, new ALLDataDictTableNames());
-            } else {
-                // OB 版本 < 2.2.70
-                return new OBOracleLessThan2270SchemaAccessor(syncJdbcExecutor, new ALLDataDictTableNames());
-            }
+            return DBSchemaAccessorGenerator.createForOBOracle(syncJdbcExecutor,
+                    dbVersion);
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/db/browser/DBSchemaAccessors.java:74]: useless breaking lines, sorry code obsessive-compulsive disorder 🙃

File: server/plugins/schema-plugin-odp-sharding-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/odpsharding/obmysql/ODPShardingOBMySQLTableExtension.java [hunk 7]
```diff
@@ -50,13 +53,18 @@ public DBTable getDetail(@NonNull Connection connection, @NonNull String schemaN
...
     protected DBSchemaAccessor getSchemaAccessor(Connection connection) {
-        return new ODPOBMySQLSchemaAccessor(JdbcOperationsUtil.getJdbcOperations(connection));
+        return DBSchemaAccessorGenerator.createForODPOBMySQL(JdbcOperationsUtil.getJdbcOperations(connection));
     }
 
     @Override
     protected DBStatsAccessor getStatsAccessor(Connection consoleConnection) {
         // only use DBStatsAccessor.getTableStats() method in plugin, so we do not use connectionId
-        return new ODPOBMySQLStatsAccessor("");
+        return DBStatsAccessorGenerator.createForODPOBMySQL("");
```
Comment (yhilmare) [inline server/plugins/schema-plugin-odp-sharding-ob-mysql/src/main/java/com/oceanbase/odc/plugin/schema/odpsharding/obmysql/ODPShardingOBMySQLTableExtension.java:62]: why should we give it an empty string but null value?

File: libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_1_x.yaml (hunk 4 above)
Comment (yhilmare) [reply libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_1_x.yaml:2]: just suggestion, I may not be solved by this pr~

File: libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleLessThan400SchemaAccessor.java (hunk 3 above)
Comment (PeachThinking) [reply libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/oracle/OBOracleLessThan400SchemaAccessor.java:53]: no, the only difference is the yaml file

File: libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/generator/DBObjectEditorGenerator.java [hunk 8]
```diff
@@ -0,0 +1,37 @@
...
+
+import com.oceanbase.tools.dbbrowser.editor.DBObjectEditor;
+
+/**
+ * @author jingtian
+ * @date 2024/5/22
+ * @since ODC_release_4.3.0
+ */
+public abstract class DBObjectEditorGenerator<T extends DBObjectEditor> {
+    public abstract T createForOBMySQL(String dbVersion);
```
[the remark this answers is not in the document]
Comment (PeachThinking) [reply libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/editor/generator/DBObjectEditorGenerator.java:26]: because abstract method can not be static，but i think we need these abstract method for DBObjectEditor

File: libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_1_x.yaml (hunk 4 above)
Comment (PeachThinking) [reply libs/db-browser/src/main/resources/schema/sql/oboracle/oboracle_4_1_x.yaml:2]: i agree

**Review by yhilmare — APPROVED** [review]
lgtm, the generator of schemaAccessor, ObjectEditor will be refactor in other prs

**Review by yhilmare — APPROVED** [review]
lgtm, the generator of schemaAccessor, ObjectEditor will be refactor in another pr

**Review by yizhouxw — APPROVED** [review]

**Review by MarkPotato777 — APPROVED** [review]
LGTM
