### PR TITLE
fix(connect-plugin): failed to connect to native percona mysql datasource when there is "-" in DBVersion String

### LINKED ISSUE #1109: [Bug]: failed to connect to native percona mysql datasource
### ODC version

4.2.3

### OB version

```shell
MySQL [(none)]> show variables like 'innodb_version';
+----------------+-----------+
| Variable_name  | Value     |
+----------------+-----------+
| innodb_version | 5.7.35-38 |
+----------------+-----------+
1 row in set (0.00 sec)
```

### What happened?

1. prepare a percona mysql datasource, you can build this env by steps as follow:
```shell
$sudo docker pull docker.io/percona
$sudo docker run -d -p 13307:3306 -e MYSQL_ROOT_PASSWORD=admin -e CLUSTER_NAME=c1 -e CLUSTER_JOIN=n1 --name mysql_percona docker.io/percona:latest
$mysql -h172.17.0.2 -uroot -padmin
```
2. add this datasource to odc and attempt to use it:
lQLPKH1cpazpV9_NAn_NCWCwouE458Ywrb8FZ5sxo13GAQ_2400_639
lQLPJw_uBatQl9_NAY_NAq-w9RQtWHNpnpoFZ5sxo13GAA_687_399

here is the log:
```shell
[2023-12-11 16:01:26.764][http-nio-8989-exec-6][4d649a7f77494f34,,6SAQ1H8JMVM21JASCMBCQ3][INFO][com.oceanbase.odc.server.web.controller.RestExceptionHandler][375]: ODC_FAILED_REQUEST, httpMethod=POST, fullURL=https://ob-odc.gz.cvte.cn/api/v2/datasource/datasources/1000001/sessions?currentOrganizationId=1&holdErrorTip=true, remoteHost=172.20.111.27, clientAddress=172.20.111.27,  handler=com.oceanbase.odc.server.web.controller.v2.ConnectSessionController#createSessionByDataSource[1 args], exceptionType=NumberFormatException, message=For input string: "25-28", rootReason=   at [com.oceanbase.odc.com](https://com.oceanbase.odc.com/)mon.util.VersionU[tils.com](https://tils.com/)pareVersions(VersionUtils.java:53)     at java.lang.Integer.parseInt(Integer.java:615)         at java.lang.Integer.parseInt(Integer.java:580)         at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) java.lang.NumberFormatException: For input string: "25-28", perfLevel=P1, response=ErrorResponse(error=Error(code=BadRequest, message=错误的请求，详情：BadRequest exception, type=NumberFormatException, message=For input string: "25-28", details=[Error.Detail(code=BadRequest, target=null, message=BadRequest exception, type=NumberFormatException, message=For input string: "25-28"), Error.Detail(code=NumberFormatException, target=null, message=For input string: "25-28")]), code=BadRequest, message=错误的请求，详情：BadRequest exception, type=NumberFormatException, message=For input string: "25-28")
```

### What did you expect to happen?

use this mysql datasource normally

### How can we reproduce it (as minimally and precisely as possible)?

follow 'what happened'

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by PeachThinking**
#### What type of PR is this?
type-bug
module-connect-plugin

#### What this PR does / why we need it:
fix `VersionUtils#compareVersions` method throws ` java.lang.NumberFormatException.forInputString`  exception when there is "-" in DBVersion String.

#### Which issue(s) this PR fixes:

Fixes #1109

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLInformationExtension.java [hunk 1]
```diff
@@ -54,7 +54,14 @@ public String getDBVersion(Connection connection) {
             throw new BadRequestException(ErrorCodes.QueryDBVersionFailed,
                     new Object[] {"Result set is empty"}, "Result set is empty");
         }
-        return dbVersion;
+        return parseDBVersion(dbVersion);
+    }
+
+    private String parseDBVersion(String version) {
+        if (version.contains("-")) {
```
Comment (yhilmare) [inline server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLInformationExtension.java:61]: why should we use first index of it, nor the second one?

Comment (yhilmare) [reply server/plugins/connect-plugin-mysql/src/main/java/com/oceanbase/odc/plugin/connect/mysql/MySQLInformationExtension.java:61]: 👏great

**Review by yhilmare — APPROVED** [review]
lgtm
