### PR TITLE
fix(sql): the sql of modifying session parameter in oracle is error

### LINKED ISSUE #2736: [Bug]: oracle datasource nls_date_format do not use "set "command
### ODC version

ODC 4.3.0 

### OB version

it is not ob ,it is oracle

### What happened?

set command is used to mysql or ob database ,not use to oracle. 
截屏2024-06-13 10 08 13

### What did you expect to happen?

"set parameter_xxx=aaa"  change to "alter session set parameter_xxx=aaa"

### How can we reproduce it (as minimally and precisely as possible)?

"set parameter_xxx=aaa"  change to "alter session set parameter_xxx=aaa"

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by zijiacj**
#### Which issue(s) this PR fixes:

Fixes #2736

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yhilmare — DISMISSED** [review]
lgtm

File: server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/SessionExtensionPoint.java [hunk 1]
```diff
@@ -34,4 +34,6 @@ public interface SessionExtensionPoint extends ExtensionPoint, SessionOperations
     String getCurrentSchema(Connection connection);
 
     String getVariable(Connection connection, String variableName);
+
+    String getAlterSessionVariableStatement(String variableScope, String variableName, String variableValue);
```
Comment (yhilmare) [inline server/plugins/connect-plugin-api/src/main/java/com/oceanbase/odc/plugin/connect/api/SessionExtensionPoint.java:38]: the method name is not so good, we should not emphasize conference in method names

File: server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleSessionExtension.java [hunk 2]
```diff
@@ -89,4 +89,9 @@ public String getVariable(@NonNull Connection connection, @NonNull String variab
         }
         return value;
     }
+
+    @Override
+    public String getAlterVariableStatement(String variableScope, String variableName, String variableValue) {
```
Comment (yhilmare) [inline server/plugins/connect-plugin-oracle/src/main/java/com/oceanbase/odc/plugin/connect/oracle/OracleSessionExtension.java:94]: how to process global/system parameter altering?

**Review by yhilmare — APPROVED** [review]
lgtm
