### PR TITLE
fix(data viewing): get result-set timeout

### LINKED ISSUE #2849: [Bug]: Unable to view table data, reports 'get result timeout'
### ODC version

ODC431

### OB version

independent

### What happened?

Unable to view table data, reports 'get result timeout'
image

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

。

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by zijiacj**
#### Which issue(s) this PR fixes:

Fixes #2849

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java [hunk 1]
```diff
@@ -339,7 +339,7 @@ public AsyncExecuteResultResp getMoreResults(@NotNull String sessionId, String r
         int timeout = Objects.isNull(timeoutSeconds) ? DEFAULT_GET_RESULT_TIMEOUT_SECONDS : timeoutSeconds;
         boolean shouldRemoveContext = context.isFinished();
         try {
-            List<JdbcGeneralResult> resultList = context.getMoreSqlExecutionResults(timeout);
+            List<JdbcGeneralResult> resultList = context.getMoreSqlExecutionResults(timeout * 1000);
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/session/ConnectConsoleService.java:342]: we may rename the variable to show the unit of this time, suggestion: gettingResultTimeoutSeconds

**Review by yhilmare — APPROVED** [review]
lgtm
