### PR TITLE
fix(logicaldatabase): generate wrong ddl when alter table

### LINKED ISSUE #3448: [Bug]: An error message is reported in a field added to a logical table
### ODC version

odc 4.3.2

### OB version

no related

### What happened?

Select a logical table, click View Table Structure, and add fields, indexes, constraints, and system errors in the Table Information display box
image
Image

### What did you expect to happen?

Logical tables can add fields, indexes, and constraints normally.

### How can we reproduce it (as minimally and precisely as possible)?

Add fields, indexes, and constraints to the logical table, click Next to confirm the SQL, and an error is reported

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by MarkPotato777**
#### What type of PR is this?

type-bug
#### What this PR does / why we need it:
When creating tables, users need to enter a logical table expression, so we need to preHandle the schema and table names; while altering tables, we should not pre handle it because we only need to treat the logical table as the physical table.
#### Which issue(s) this PR fixes:

Fixes #3448 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java [hunk 1]
```diff
@@ -143,7 +143,6 @@ public void run() {
                     physicalTableEntity.setOrganizationId(logicalDatabase.getOrganizationId());
                     physicalTableEntity.setPhysicalDatabaseId(dataNode.getDatabaseId());
                     physicalTableEntity.setPhysicalDatabaseName(dataNode.getSchemaName());
-                    physicalTableEntity.setLogicalTableId(dataNode.getTableId());
```
Comment (MarkPotato777) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/connection/logicaldatabase/LogicalTableExtractTask.java:146]: Fix wrongly setting the logicalTableId which is a typo/mistake
