### PR TITLE
fix(migrate): fix login process resource load faild

### LINKED ISSUE #2880: [Bug]: Login failed
### ODC version

odc431

### OB version

*

### What happened?

image

### What did you expect to happen?

Login successful

### How can we reproduce it (as minimally and precisely as possible)?

Login to shilin/aaAA11__

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by yiminpeng**
#### What type of PR is this?
fix

#### What this PR does / why we need it:

fix login process resource load faild, caused by delete useless yaml

#### Which issue(s) this PR fixes:
Fixes #2880

#### Additional documentation e.g., usage docs, etc.:
```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/IndividualOrganizationMigrator.java [hunk 1]
```diff
@@ -99,7 +99,6 @@ private ResourceConfig getResourceConfig(DataSource dataSource, Long userId, Lon
         List<String> resourceLocations = new LinkedList<>();
         resourceLocations.add("migrate/common/V_3_2_0_6__iam_permission.yaml");
         resourceLocations.add("migrate/common/V_3_3_0_4__iam_permission.yaml");
-        resourceLocations.add("migrate/common/V_3_4_0_2__iam_permission.yaml");
```
Comment (MarkPotato777) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/IndividualOrganizationMigrator.java:102]: You may need to remove all Yaml files which were removed in your last PR, rather than only this `V_3_4_0_2__iam_permission.yaml`

Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/IndividualOrganizationMigrator.java:102]: The other two file are missing, re-pushing now. A total of three related documents.

Comment (yiminpeng) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/collaboration/IndividualOrganizationMigrator.java:102]: The other two file are missing, re-pushing now. A total of three related documents.

**Review by MarkPotato777 — APPROVED** [review]
LGTM
