### PR TITLE
fix(ticket): failed to approve ticket when input over-sized comment

### LINKED ISSUE #2554: [Bug]: The work order execution result is inconsistent with the approval status
### ODC version

ODC 4.3.0

### OB version

No related

### What happened?

When approving a database change, enter a processing opinion of more than 200 characters and click "Approve". The interface prompts "Error accessing the metadata database, please contact the administrator". The interface reports 500. Click Execute and the result sql has been executed normally. However, when clicking the task flow, the processing status is Rejected.
And the execution results and task flow are inconsistent.
image
image

### What did you expect to happen?

When reviewing, enter more than 200 characters and click Confirm. At this time, the front-end and back-end should have verification. 

### How can we reproduce it (as minimally and precisely as possible)?

When approving a work order, enter more than 200 characters to view the status of the work order

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by smallsheeeep**
#### What type of PR is this?
type-bug
module-ticket

#### What this PR does / why we need it:
When I approve a ticket and input a comment with more than 1024 chars, then exception will be thrown. And the approval status will be failed but the task still executed.

 This PR fixd it!

#### Which issue(s) this PR fixes:

Fixes #2554 

#### Special notes for your reviewer:
Self-test passed.

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java [hunk 1]
```diff
@@ -656,7 +657,10 @@ private FlowInstanceDetailResp cancel(@NotNull FlowInstance flowInstance, Boolea
         return FlowInstanceDetailResp.withIdAndType(id, taskTypeHolder.getValue());
     }
 
-    public FlowInstanceDetailResp approve(@NotNull Long id, String message, Boolean skipAuth) throws IOException {
+    @Transactional(rollbackFor = Exception.class)
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java:660]: have you tested for the transaction? the flow will be okay when transaction is rollbacked?

Comment (smallsheeeep) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/flow/FlowInstanceService.java:660]: It works

**Review by yhilmare — APPROVED** [review]
lgtm
