### PR TITLE
fix(notification): lost sign when updating channel

### LINKED ISSUE #2305: [Bug]: Edit and modify the message channel. The signature key will be deleted after saving.
### ODC version

ODC424bp2

### OB version

independent

### What happened?

Edit and modify the message channel. The signature key will be deleted after saving.
image

### What did you expect to happen?

。

### How can we reproduce it (as minimally and precisely as possible)?

Edit and modify the message channel. The signature key will be deleted after saving.

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by LuckyPickleZZ**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:

When user edit and update channel with sign, the sign would be lost after updating.
This is due to the annotation of `@OneToMany`, which caused the new `ChannelPropertyEntity` to overwrite the old ones when editing `ChannelEntity`.
This PR modifies the `save` to the `update` method of `ChannelRepository`. And abandoned the cascading updates of JPA, instead manually deleting ChannelProperty and inserting them again.

#### Which issue(s) this PR fixes:

Fixes #2305

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationService.java [hunk 1]
```diff
@@ -174,17 +174,18 @@ public Channel updateChannel(@NotNull Long projectId, @NotNull Channel channel)
...
         }
 
         ChannelEntity toBeSaved = channelMapper.toEntity(channel);
-        toBeSaved.setCreatorId(authenticationFacade.currentUserId());
-        toBeSaved.setOrganizationId(authenticationFacade.currentOrganizationId());
-        toBeSaved.setProjectId(projectId);
+        channelRepository.update(toBeSaved);
+
+        channelPropertyRepository.deleteByChannelId(channel.getId());
+        toBeSaved.getProperties().forEach(property -> channelPropertyRepository.save(property));
```
Comment (yizhouxw) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationService.java:186]: may involve performace risk ?

Comment (LuckyPickleZZ) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/notification/NotificationService.java:186]: Compared to the original @onetonay cascading update, there is no performance rollback. And since the number of properties is in single digits, there should be no performance issues.

**Review by yizhouxw — APPROVED** [review]
lgtm

**Review by smallsheeeep — APPROVED** [review]
LGTM

**Review by MarkPotato777 — APPROVED** [review]
LGTM
