### PR TITLE
fix(permission): user can create datasource without any project and role

### LINKED ISSUE #1013: [Bug]: The user does not belong to any role but has permission to create data sources
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

user：tonghan_1204
The user does not belong to any role but has permission to create data sources
image
Permissions are directly bound to users, not roles.

### What did you expect to happen?

Users' permissions are controlled by roles.

### How can we reproduce it (as minimally and precisely as possible)?

1.Grant user tonghan_1204 project tonghan administrator rights
2.Create a role that has permission to create data sources
3.Grant this role to the user
4.Revoke this role from the user

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by smallsheeeep**
#### What type of PR is this?
type-bug
module-user permission

#### What this PR does / why we need it:
In ODC 4.2.3, if a user join a project with OWNER or DBA role, then ODC  will grant `create` permission of `CONNECTION:*`  to this user. But when the user leave the project, these permission is not reclaimed. So user can create datasource without any project and role. 
In this PR, I fix it by delete the internal grant permission operation.

#### Which issue(s) this PR fixes:
Fixes #1013 #683 

#### Special notes for your reviewer:
Self-test passed

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserPermissionService.java [hunk 1]
```diff
@@ -150,6 +150,7 @@ public List<UserPermissionResp> list(@NonNull String resourceIdentifier) {
                 .collect(Collectors.toList());
     }
 
+    @Deprecated
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserPermissionService.java:153]: shall we delete these deprecated methods?

Comment (smallsheeeep) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/iam/UserPermissionService.java:153]: Yes, I confirmed it with font-end and deleted these codes.

**Review by yhilmare — APPROVED** [review]
great job 😊 ,lgtm
