### PR TITLE
fix(flowTask): fix failed to get flow task results

### LINKED ISSUE #1962: [Bug]: The commit mode setting in personal settings is not taking effect for the Oracle database.
### ODC version

4.2.4

### OB version

NULL

### What happened?

When I set the commit mode to manual for the Oracle database, the transaction commits are still occurring automatically.
image

### What did you expect to happen?

When I configure the Oracle mode to manual commit, the transactions are committed manually.

### How can we reproduce it (as minimally and precisely as possible)?

open an oracle database，then djusting commit mode

### Anything else we need to know?

_No response_

### Cloud

_No response_

### LINKED ISSUE #1965: [Bug]: The execution time of alter type is displayed as 0
### ODC version

ODC 4.2.4

### OB version

Oracle 11g

### What happened?

The execution time of alter type sql cannot be obtained, but it is displayed as 0 in the ODC sql console
image
image

### What did you expect to happen?

f the execution time cannot be queried, it will be displayed as '-'.

### How can we reproduce it (as minimally and precisely as possible)?

Execute the following sql statement and check the execution time
alter table test add y int;

### Anything else we need to know?

_No response_

### Cloud

_No response_

### LINKED ISSUE #1979: [Bug]: failed to get flow task result
### ODC version

4.2.4

### OB version

all

### What happened?

the response of interface :/api/v2/flow/flowInstances/39/tasks/result?currentOrganizationId=1 is null
image

### What did you expect to happen?

return taskResult success

### How can we reproduce it (as minimally and precisely as possible)?

1. create a new mock data or database change or structure compare task
2. Click to view task details

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by PeachThinking**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:
fix several bug:
1. fix failed to covert json to taskResult class, the root cause is taskResult is save as a List in `BaseODCFlowTaskDelegate#setDownloadLogUrl`
2. fix the DB execution time of alter type sql is always displayed as 0，because we cannot query the time consuming of alter sql in `SYS.V$SQL`
3. fix the commit mode setting in personal settings is not taking effect for the Oracle database

#### Which issue(s) this PR fixes:

Fixes #1962
Fixes #1965 
Fixes #1979 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java [hunk 1]
```diff
@@ -355,9 +355,10 @@ private void setDownloadLogUrl(@NonNull Long flowInstanceId) throws IOException,
         List<? extends FlowTaskResult> flowTaskResults = flowTaskInstanceService.getTaskResultFromEntity(taskEntity);
         Verify.singleton(flowTaskResults, "flowTaskResults");
         if (flowTaskResults.get(0) instanceof AbstractFlowTaskResult) {
-            AbstractFlowTaskResult abstractFlowTaskResult = (AbstractFlowTaskResult) flowTaskResults.get(0);
+            FlowTaskResult flowTaskResult = flowTaskResults.get(0);
+            AbstractFlowTaskResult abstractFlowTaskResult = (AbstractFlowTaskResult) flowTaskResult;
             abstractFlowTaskResult.setFullLogDownloadUrl(downloadUrl);
-            taskEntity.setResultJson(JsonUtils.toJson(flowTaskResults));
+            taskEntity.setResultJson(JsonUtils.toJson(flowTaskResult));
```
Comment (smallsheeeep) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/BaseODCFlowTaskDelegate.java:361]: LGTM

**Review by smallsheeeep — APPROVED** [review]

**Review by LuckyPickleZZ — APPROVED** [review]
lgtm

**Review by yhilmare — APPROVED** [review]
lgtm
