### PR TITLE
fix(apply-project): project role names are not internationalized

### LINKED ISSUE #980: [Bug]: The permission type described in the project permission worksheet is expected to be displayed in Chinese
### ODC version

ODC 4.2.3

### OB version

-

### What happened?

image
The permission type described in the work order is in English.

### What did you expect to happen?

The permission type described in the project permission worksheet is expected to be displayed in Chinese.

### How can we reproduce it (as minimally and precisely as possible)?

Deliver the task for requesting project permissions.

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by smallsheeeep**
#### What type of PR is this?
type-bug
module-apply project permission

#### What this PR does / why we need it:
The description of apply project permission ticket generated by ODC is not internationalized. This is because the `ResourceRoleName` is not internationalized and this PR fix it.

#### Which issue(s) this PR fixes:
Fixes #980 

#### Special notes for your reviewer:
Self-test passed

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ResourceRoleBasedPermission.java [hunk 1]
```diff
@@ -43,8 +43,8 @@ public class ResourceRoleBasedPermission implements Permission {
     public ResourceRoleBasedPermission(@NonNull SecurityResource resource, @NonNull String resourceRole) {
         this.resourceId = resource.resourceId();
         this.resourceType = resource.resourceType();
-        this.resourceRoles = Arrays.stream(StringUtils.split(resourceRole, ",")).map(ResourceRoleName::fromValue)
-                .collect(Collectors.toList());
+        this.resourceRoles = Arrays.stream(StringUtils.split(resourceRole, ","))
+                .map(e -> ResourceRoleName.valueOf(e.trim())).collect(Collectors.toList());
```
Comment (yhilmare) [inline server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ResourceRoleBasedPermission.java:47]: `e.trim().toUpperCase()` may be better?

Comment (smallsheeeep) [reply server/odc-core/src/main/java/com/oceanbase/odc/core/authority/permission/ResourceRoleBasedPermission.java]: okay

**Review by yhilmare — APPROVED** [review]
lgtm
