### PR TITLE
fix(logicaldatabase): wrong generated ddl of creating and altering logical tables

### LINKED ISSUE #3375: [Bug]: When you create a logical table, you enter a table creation expression and a table creation statement is generated, but the logic database ticket fails to be executed
### ODC version

odc4.3.2

### OB version

no related 

### What happened?

image
image

When you create a logical table, you enter a table creation expression and a table creation statement is generated, but the logic database ticket fails to be executed

### What did you expect to happen?

When creating logical tables, you should avoid incorrect expressions and table creation statements

### How can we reproduce it (as minimally and precisely as possible)?

When you create a logical table, you enter a table creation expression and a table creation statement is generated, but the logic database ticket fails to be executed

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by MarkPotato777**
#### What type of PR is this?

type-bug
#### What this PR does / why we need it:
When generating logical table ddl, it should ignore the logical database name, and use the user-defined logical table expression.
#### Which issue(s) this PR fixes:

Fixes #3375 

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

**Review by yhilmare — APPROVED** [review]
lgtm

File: server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java [hunk 1]
```diff
@@ -209,4 +212,18 @@ private TableExtensionPoint getTableExtensionPoint(@NotNull ConnectionSession co
         return SchemaPluginUtil.getTableExtension(connectionSession.getDialectType());
     }
 
+    private void preHandleLogicalTable(DBTable table) {
+        String relation = table.getName();
+        if (StringUtils.isEmpty(relation)) {
+            throw new IllegalArgumentException("logical table expression should not be empty");
+        }
+        String[] segments = StringUtils.split(relation, ".");
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/db/DBTableService.java:220]: how to handle such input: `table_name(0_9)` which does not contain schema
