### PR TITLE
fix(structure-compare): show incorrect precision of tinyint datatype in mysql mode

### LINKED ISSUE #3395: [Bug]: The table structure synchronization result is inconsistent
### ODC version

4.3.1

### OB version

mysql

### What happened?

The table structure synchronization result is inconsistent.

### What did you expect to happen?

The table structure synchronization result is consistent.

### How can we reproduce it (as minimally and precisely as possible)?

1. create table in source database
```
create table `tinyint_test`(`del_flag` tinyint(4) UNSIGNED  ZEROFILL  DEFAULT '0' COMMENT '0 正常 1 删除' NOT NULL);
```
2. create structure comparison task
3. execute comparison result
4. create structure comparison task again
### Anything else we need to know?

_No response_

### LINKED ISSUE #3415: [Bug]: the precision of the tinyint type is incorrect in mysql mode
### ODC version

all

### OB version

mysql 5.7

### What happened?

the precision of the tinyint type is incorrect in mysql mode:
table ddl:
image
odc show precision:
image

### What did you expect to happen?

show the precision of the tinyint type correctly

### How can we reproduce it (as minimally and precisely as possible)?

create table with tinyint(n), n can be any, odc will always show precision 3:
```
create table `tinyint_test7`(`del_flag` tinyint(4) UNSIGNED  ZEROFILL  DEFAULT '0' COMMENT '0 正常 1 删除' NOT NULL);
```

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by PeachThinking**
#### What type of PR is this?
type-bug
module-structure compare

#### What this PR does / why we need it:
Regardless of the precision defined for the `tinyint` field type in the table's ddl, the value of the `NUMERIC_PRECISION` field in the `information_schema.columns` table is always be 3.
table ddl:
```
create table `tinyint_test`(`del_flag` tinyint(4) UNSIGNED ZEROFILL DEFAULT '0' );
```
query result：
image
so we can get correctly precision by parse `COLUMN_TYPE`.
we already have a method called `fillPrecisionAndScale` which only used in `OBMySQLNoGreaterThan1479SchemaAccessor`, so i remove the method to `MySQLNoLessThan5700SchemaAccessor`

#### Which issue(s) this PR fixes:

Fixes #3395
Fixes #3415

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/mysql/DefaultDBStructureComparatorTest.java [hunk 1]
```diff
@@ -0,0 +1,136 @@
...
+
+        jdbcTemplate.execute("use `" + sourceSchemaName + "`");
+        jdbcTemplate.execute(sourceDrop);
+        jdbcTemplate.execute(sourceSchemaDdl);
+        jdbcTemplate.execute("use `" + targetSchemaName + "`");
+        jdbcTemplate.execute(targetDrop);
+        jdbcTemplate.execute(targetSchemaDdl);
+        jdbcTemplate.execute("use `" + configuration.getDefaultDBName() + "`");
+
+        results = comparator.compare(getSourceConfig(srcConfiguration),
```
Comment (yizhouxw) [inline server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/mysql/DefaultDBStructureComparatorTest.java:87]: under test method should called in test case, not in setUp

Comment (PeachThinking) [reply server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/mysql/DefaultDBStructureComparatorTest.java:87]: In fact, all compare methods of the structure comparison class are implemented in setUp. This is because we only need to read the ddl script once and compare it once to obtain the comparison results of all unit tests, which can also improve the efficiency of unit testing.

File: libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java [hunk 2]
```diff
@@ -110,6 +110,18 @@ public class MySQLNoLessThan5700SchemaAccessor implements DBSchemaAccessor {
 
     protected JdbcOperations jdbcOperations;
     protected DBSchemaAccessorSqlMapper sqlMapper;
+    private static final Set<String> SPECIAL_TYPE_NAME = new HashSet<>();
```
[the remark this answers is not in the document]
Comment (PeachThinking) [reply libs/db-browser/src/main/java/com/oceanbase/tools/dbbrowser/schema/mysql/MySQLNoLessThan5700SchemaAccessor.java]: ok~

**Review by yhilmare — APPROVED** [review]
lgtm

File: server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/mysql/DefaultDBStructureComparatorTest.java (hunk 1 above)
Comment (yizhouxw) [reply server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/mysql/DefaultDBStructureComparatorTest.java:87]: the basic concept is wrong here

Comment (yizhouxw) [reply server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/mysql/DefaultDBStructureComparatorTest.java:87]: if only once comparing, the only one test case

Comment (PeachThinking) [reply server/integration-test/src/test/java/com/oceanbase/odc/service/structurecompare/mysql/DefaultDBStructureComparatorTest.java:87]: but each test case is written for a different test scenario, and it is not appropriate to write all of them in one test method. I think just consider the test class for structure comparison  as a special scenario, which compares all table structures at once.

**Review by yizhouxw — APPROVED** [review]
lgtm

**Review by yhilmare — APPROVED** [review]
lgtm
