### PR TITLE
fix(database-change): failed to check if time-consuming sql exists in personal space

### LINKED ISSUE #1710: [Bug]: The logic of optimizing personal space without index changes and timeout
### ODC version

odc424

### OB version

*

### What happened?

The timeout execution time for database changes has not changed

### What did you expect to happen?

The logic of optimizing personal space over time

### How can we reproduce it (as minimally and precisely as possible)?

Personal space execution database changes

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by PeachThinking**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:
This pr is abandoned：https://github.com/oceanbase/odc/pull/1578/files
Delete `IndexChangeTimeConsumingExists` class，the logic to detect whether time-consuming index changes sql exists is placed in the `DatabaseChangeRuntimeFlowableTask#modifyTimeoutIfTimeConsumingSqlExists` and `DatabaseChangeRuntimeFlowableTaskCopied#modifyTimeoutIfTimeConsumingSqlExists` method，so that it will be detected in both personal space and team space. 
In the worst case, in the database change task under the team space, all sql will be parsed twice.

#### Which issue(s) this PR fixes:

Fixes #1710

#### Additional documentation e.g., usage docs, etc.:

```docs

```

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java [hunk 1]
```diff
@@ -203,26 +219,67 @@ private DatabaseChangeThread generateOdcAsyncTaskThread(Long taskId, DelegateExe
...
+                    databaseChangeFileReader.readInputStreamFromSqlObjects(parameters, bucketName, -1);
+            if (uploadFileInputStream != null) {
+                uploadFileSqlIterator =
+                        SqlUtils.iterator(dialectType, delimiter, uploadFileInputStream, StandardCharsets.UTF_8);
+            }
+        }
+        while (CollectionUtils.isNotEmpty(userInputSqls)
+                || (uploadFileSqlIterator != null && uploadFileSqlIterator.hasNext())) {
+            String sql = CollectionUtils.isNotEmpty(userInputSqls) ? userInputSqls.remove(0).getStr()
+                    : uploadFileSqlIterator.next().getStr();
```
Comment (krihy) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java:246]: remove element in iterator in loop  is unsafe operation,  suggest  use iterator

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java [hunk 2]
```diff
@@ -203,26 +219,67 @@ private DatabaseChangeThread generateOdcAsyncTaskThread(Long taskId, DelegateExe
...
-            this.autoModifyTimeout = true;
-            parameters.setTimeoutMillis(autoModifiedTimeout);
-            TaskEntity databaseChangeTaskEntity = taskService.detail(taskId);
-            databaseChangeTaskEntity.setParametersJson(JsonUtils.toJson(parameters));
-            taskService.updateParametersJson(databaseChangeTaskEntity);
+        List<OffsetString> userInputSqls = null;
+        SqlStatementIterator uploadFileSqlIterator = null;
+        String delimiter = parameters.getDelimiter();
+        if (StringUtils.isNotBlank(parameters.getSqlContent())) {
+            userInputSqls = SqlUtils.splitWithOffset(dialectType, parameters.getSqlContent(), delimiter);
```
Comment (krihy) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java:232]: sql content may contains comment, like 'ALTER T ADD  INDEX IDX_1 ; -- some comments', 
spilt result is two sql ['ALTER T ADD  INDEX IDX_1', 'some comments'], second sql is invalid, 
suggest spit with remove comment

File: server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java [hunk 3]
```diff
@@ -1168,19 +1167,6 @@ public void buildCheckResults_servalResultExist_orderSucceed() {
         Assert.assertEquals(expect, actual);
     }
 
-    @Test
-    public void check_timeConsumingIndexChangeExists_violationGenerated() {
```
Comment (krihy) [inline server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java:1172]: why delete test case ?

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java (hunk 2 above)
Comment (smallsheeeep) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java:232]: I can not unstand you mention. The comments will not be a whole SQL even spit without remove comment.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java [hunk 4]
```diff
@@ -203,26 +219,67 @@ private DatabaseChangeThread generateOdcAsyncTaskThread(Long taskId, DelegateExe
     }
 
     private void modifyTimeoutIfTimeConsumingSqlExists(DelegateExecution execution,
-            DatabaseChangeParameters parameters) {
-        if (!parameters.isModifyTimeoutIfTimeConsumingSqlExists()) {
+            DatabaseChangeParameters parameters, DialectType dialectType, Long creatorId) {
+        long autoModifiedTimeout = flowTaskProperties.getIndexChangeMaxTimeoutMillisecond();
```
Comment (smallsheeeep) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java:223]: What will happen if exception occurs inner this method? For example, the SQL is invalid and exception will be thrown when parse SQL. I thought that the task will be failed but these error message may not displaied in the log file. So better to put these codes in a try-catch block. There are two ways:
1. Throw a exception and then abort the task;
2. Skip this operation and contine the task.

I prefer the second way.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java [hunk 5]
```diff
@@ -226,30 +239,68 @@ private JobDefinition buildJobDefinition(DelegateExecution execution, TaskEntity
                 .build();
     }
 
-    private void modifyTimeoutIfTimeConsumingSqlExists(DelegateExecution execution, DatabaseChangeParameters parameters,
-            DatabaseChangeTaskParameters taskParameters, TaskEntity taskEntity) {
-        if (!parameters.isModifyTimeoutIfTimeConsumingSqlExists()) {
+    private void modifyTimeoutIfTimeConsumingSqlExists(DatabaseChangeParameters parameters,
+            DatabaseChangeTaskParameters taskParameters, TaskEntity taskEntity, DialectType dialectType,
```
Comment (smallsheeeep) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java:243]: Same as above. Solve the exception.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java [hunk 6]
```diff
@@ -226,30 +239,68 @@ private JobDefinition buildJobDefinition(DelegateExecution execution, TaskEntity
...
-        long autoModifiedTimeout = flowTaskProperties.getIndexChangeMaxTimeoutMillisecond();
+        List<OffsetString> userInputSqls = null;
+        SqlStatementIterator uploadFileSqlIterator = null;
+        if (StringUtils.isNotBlank(parameters.getSqlContent())) {
+            userInputSqls = SqlUtils.splitWithOffset(dialectType, parameters.getSqlContent(),
+                    parameters.getDelimiter());
+        }
+        if (CollectionUtils.isNotEmpty(parameters.getSqlObjectIds())) {
+            String bucketName = "async".concat(File.separator).concat(creatorId.toString());
+            InputStream uploadFileInputStream =
```
Comment (smallsheeeep) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTaskCopied.java:259]: Same as abov. Close the inputstream.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/SqlCheckTaskResult.java [hunk 7]
```diff
@@ -48,10 +48,9 @@ public class SqlCheckTaskResult implements Serializable, FlowTaskResult {
     private String error;
     private String fileName;
     private List<CheckResult> results = new ArrayList<>();
-    private boolean timeConsumingSqlExists;
 
-    public static SqlCheckTaskResult success(@NonNull List<CheckViolation> violations,
-            @NonNull boolean timeConsumingSqlExists) {
+    public static SqlCheckTaskResult success(
+            @NonNull List<CheckViolation> violations) {
```
Comment (smallsheeeep) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/model/SqlCheckTaskResult.java:53]: Merge the code to one line.

File: server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java (hunk 3 above)
Comment (PeachThinking) [reply server/odc-service/src/test/java/com/oceanbase/odc/service/sqlcheck/OracleSqlCheckerTest.java:1172]: because i deleted `IndexChangeTimeConsumingExists` class.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java (hunk 2 above)
Comment (krihy) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java:232]: comments  will be treat as sql

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java (hunk 4 above)
Comment (PeachThinking) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java:223]: You are right. I would add try catch in this method. 
but parse SQL exception was caught  in `SqlCheckUtil#parseSingleSql`.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java (hunk 2 above)
Comment (PeachThinking) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java:232]: There is really no need to return comment here. 
will use `SqlUtils.splitWithOffset(dialectType, parameters.getSqlContent(), delimiter, true)` method

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java (hunk 1 above)
Comment (PeachThinking) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java:246]: The object being iterated and the object being revomed are not the same

File: server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java [hunk 8]
```diff
@@ -203,26 +219,67 @@ private DatabaseChangeThread generateOdcAsyncTaskThread(Long taskId, DelegateExe
...
-            taskService.updateParametersJson(databaseChangeTaskEntity);
+        List<OffsetString> userInputSqls = null;
+        SqlStatementIterator uploadFileSqlIterator = null;
+        String delimiter = parameters.getDelimiter();
+        if (StringUtils.isNotBlank(parameters.getSqlContent())) {
+            userInputSqls = SqlUtils.splitWithOffset(dialectType, parameters.getSqlContent(), delimiter);
+        }
+        if (CollectionUtils.isNotEmpty(parameters.getSqlObjectIds())) {
+            String bucketName = "async".concat(File.separator).concat(creatorId.toString());
+            InputStream uploadFileInputStream =
```
[the remark this answers is not in the document]
Comment (PeachThinking) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/flow/task/DatabaseChangeRuntimeFlowableTask.java]: Done.

**Review by smallsheeeep — DISMISSED** [review]
LGTM

**Review by yhilmare — APPROVED** [review]
lgtm

**Review by yizhouxw — APPROVED** [review]
lgtm
