### PR TITLE
fix(result-set): failed export oracle result set

### LINKED ISSUE #1931: [Bug]: Resultset export failed due to query timeout
### ODC version

4.2.4

### OB version

any

### What happened?

Resultset export failed due to query timeout when query SQL result set meta data by:
```java
SyncJdbcExecutor syncJdbcExecutor = session.getSyncJdbcExecutor(ConnectionSessionConstants.BACKEND_DS_KEY);
ResultSetMetaData rsMetaData =syncJdbcExecutor.query(parameter.getSql(), pss -> pss.setMaxRows(10),ResultSet::getMetaData);
```

### What did you expect to happen?

Avoid timeout.

### How can we reproduce it (as minimally and precisely as possible)?

Export SQL result with long query time.

### Anything else we need to know?

_No response_

### Cloud

_No response_

### PR DESCRIPTION
**Pull request by LuckyPickleZZ**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:

This PR fixes 2 issues:
1. We use ojdbc for oracle, and when a statement has been closed , the `ResultSetMetaData` could not be accessed any more. It has to be accessed in a statement.
2. If a query would be executed over default query timeout, the result set export task will fail. So we change this parameter before query.

#### Which issue(s) this PR fixes:

Fixes #1931 #1943

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java [hunk 1]
```diff
@@ -266,6 +276,21 @@ private void setColumnConfig(DataTransferConfig config, ResultSetExportTaskParam
         }
     }
 
+    private String getTimeoutSettingStatement(DialectType dialectType) {
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java:279]: you may use this for timeout setting
ConsoleTimeoutInitializer

File: server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java [hunk 2]
```diff
@@ -266,6 +276,21 @@ private void setColumnConfig(DataTransferConfig config, ResultSetExportTaskParam
...
+        switch (dialectType) {
+            case OB_MYSQL:
+            case OB_ORACLE:
+            case ODP_SHARDING_OB_MYSQL:
+                return "set ob_query_timeout = " + DEFAULT_TIMEOUT_SECONDS * 1000000L;
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java:284]: we may not set this timeout settings by a static field, shall we add this parameter to the `ResultSetExportTaskParameter`?

we can give it a default value cause the front end does not set it~

Comment (LuckyPickleZZ) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java]: sure, I added a parameter in `ResultSetExportTaskParameter `

File: server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java (hunk 1 above)
Comment (LuckyPickleZZ) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTask.java]: thanks, updated.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTaskParameter.java [hunk 3]
```diff
@@ -49,6 +49,7 @@ public class ResultSetExportTaskParameter implements Serializable, TaskParameter
     private List<MaskingAlgorithm> rowDataMaskingAlgorithms;
     @JsonIgnore
     private String database;
+    private Integer executionTimeoutSeconds = 48 * 60 * 60;
```
Comment (smallsheeeep) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTaskParameter.java:52]: 48h seems too long, we cannot accept that init a task needing 48 hours.

Comment (LuckyPickleZZ) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTaskParameter.java:52]: Maybe we cannot avoid this. If user requests to export a query with `/*+ timeout */` hint, it would be executed for a long duration anyway.
And this timeout param does not take effect during task initialization, but rather during task execution. So it should not have a serious impact.

**Review by PeachThinking — APPROVED** [review]
LGTM

File: server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTaskParameter.java (hunk 3 above)
Comment (smallsheeeep) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/resultset/ResultSetExportTaskParameter.java:52]: I got you!
