### PR TITLE
fix(obclient): remove unexpected characters to avoid obclient display incorrectly

### LINKED ISSUE #2301: [Bug]: The command line window displays an incorrect sql file that is too long
### ODC version

ODC 4.2.4-bp

### OB version

-

### What happened?

Typing too long sql in the command-line window does not display correctly.
image

### What did you expect to happen?

Typing long sql in a command-line window displays correctly.

### How can we reproduce it (as minimally and precisely as possible)?

Enter the following sql in the command line window.
```
SELECT TENANT_ID, TENANT_NAME, TENANT_ROLE, STATUS, SWITCHOVER_STATUS, SYNC_SCN, REPLAYABLE_SCN,READABLE_SCN, RECOVERY_UNTIL_SCN FROM oceanbase.DBA_OB_TENANTS where tenant_type<>'META';
```

### Anything else we need to know?

_No response_

### PR DESCRIPTION
**Pull request by LuckyPickleZZ**
#### What type of PR is this?
type-bug

#### What this PR does / why we need it:

When input a long sequence in obclient, it would return a sequence with ` \r` in it. And it would cause the cursor going back to head of the line . 
So we replace these unexpected characters manually.

#### Which issue(s) this PR fixes:

Fixes #2301

### CODE REVIEW

File: server/odc-service/src/main/java/com/oceanbase/odc/service/websocket/OBClientReadThread.java [hunk 1]
```diff
@@ -28,6 +29,8 @@
 
 @Slf4j
 public class OBClientReadThread extends Thread {
+    private static final Pattern UNEXPECTED_SEQUENCE_PATTERN = Pattern.compile(" \\r");
```
Comment (yhilmare) [inline server/odc-service/src/main/java/com/oceanbase/odc/service/websocket/OBClientReadThread.java:32]: what is the white space of this pattern used for? `\\s`?

**Review by yizhouxw — DISMISSED** [review]
lgtm,

current only windows/linux support command line windows,
windows user `\r\n`, linux use `\n` as line separator, but windows is compatible with `\n` also.

File: server/odc-service/src/main/java/com/oceanbase/odc/service/websocket/OBClientReadThread.java (hunk 1 above)
Comment (yizhouxw) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/websocket/OBClientReadThread.java:32]: white space may not  affect line breaking behavior

Comment (yizhouxw) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/websocket/OBClientReadThread.java:32]: ` \\r` may change to `\\r`

Comment (LuckyPickleZZ) [reply server/odc-service/src/main/java/com/oceanbase/odc/service/websocket/OBClientReadThread.java:32]: We should not change this , because the obclient error sequences are always with a blank space~
image

**Review by yhilmare — APPROVED** [review]
lgtm

**Review by yizhouxw — APPROVED** [review]
lgtm
